### ISSUE TITLE
Script Disassembler

### ISSUE THREAD

**Issue by danhedron** [rwengine/openrw#10]
To increase the utility of the script debugger, it would be nice if we could display a simple disassembly of the game script surrounding the program counter. This is easy enough in the forward direction, since the instruction size is known, but is difficult to reliably reverse.

To make it possible to show instructions behind the program counter as well as ahead, parsing of the instructions could be done with a Disassembler that accepts the known VM opcode definitions and hard-coded funky business the SCM does, producing an in-order list of all the instruction addresses within the SCM file.

**Comment by JayFoxRox** [comment]
If we are talking about the http script debugger here, that was ripped out as part of #181 .
Shall this be closed?

**Comment by danhedron** [comment]
There are better tools for this now, no need for us to worry about it directly.
