### ISSUE TITLE
Inconsistent code styling

### ISSUE THREAD

**Issue by Djhg2000** [rwengine/openrw#100]
There are several variants of code styling used in the source, for example all of the styles below can be found in rwgame/ingamestate.cpp:

Line 203:
> if (exp) {
> [tab]func();
> }

Line 219:
> if (exp)
> {
> [tab]func();
> }

Line 397 (probably a typo):
> [tab]if (
> [tab][tab][tab][tab][tab]exp)
> {
> [tab]func();
> }

I'm fine with either of the first two (the second seems to be more common) but without a common style it's sometimes a bit confusing to follow the code and as a consequence the third one looks to me like the work of a buggy IDE.

I'd suggest the following based on the majority in ingamestate.cpp but again the important thing is to have a well defined coding style at all:

> if (exp)
> {
> [tab]func();
> }

The decision is not mine to make but that's my suggestion.

Edit: the comment system is completely removing whitespaces, I really should use the preview feature more often.

Edit 2: the third example was incorrectly represented.

**Comment by Hockenberry** [comment]
I would recommend using clang-format. There exists a plugin for [Visual Studio](http://llvm.org/builds/) and for [Xcode](https://github.com/travisjeffery/ClangFormat-Xcode) too. 

Personally I enable source code formatting under Xcode as a save action. 

Now we need to select a [coding style](http://clang.llvm.org/docs/ClangFormatStyleOptions.html).

I would select a style which changes a selected file with minimal differences.

Using this tool could end all coding style discussions - and gives a consistent and diff-able source code.

**Comment by tsjost** [comment]
I can't be responsible for dan, but I've always done the following:

* { on new lines for namespaces, classes, methods and such
* { on same line for ifs, loops, switches etc
* No space between function names and (
* Space between language constructs and (
* No space after/before ( and ) in function calls
* Always space before and after ! (ignore previous rule in this case)
* Tabs for indentation, spaces for alignment, but alignment probably shouldn't be used.
* Include files in the order of local files, libraries and system files

```
#include "foo/local_file.hpp"

#include <some/library.hpp>

#include <systemlib>

namespace foobar
{
class Things
{
    void function_or_method(int someWords)
    {
        if ( ! someWords) {
            dostuff(someWords);
        }
    }
}

**Comment by darkf** [comment]
Gonna agree we should apply clang-format really soon -- anyone on board to make it happen?

Two cents:
- Spaces with ! is really ugly and unnecessary. `if(!x)` is perfectly legible and everyone else does it.

- While we're at it, the space before ( in `if (...)` is also ugly, but it's fine.

- Nothing wrong with braces on the same line as function declarations.

- Spaces are more consistent for indentation.

**Comment by Djhg2000** [comment]
The space before `(` in `if (...)` is standard practice; it is a statement, not a function call (which should indeed be written as `function(...)`). This is because the `(...)` in the `if` statement is an expression and is not to be confused with the arguments `...` in the `function(...)` call.

The syntactical difference being the parentheses are part of the expression itself in the statement while simply being a notation for arguments in the function call. This is why I often write `if (...)` and `function( ... )`.

For example it is perfectly valid C to write `if var` instead of `if (var)`, but any decent compiler will throw a syntax error on `function args` while accepting `function( args )`.

**Comment by darkf** [comment]
@Djhg2000 

>The space before ( in if (...) is standard practice; it is a statement, not a function call (which should indeed be written as function(...)). This is because the (...) in the if statement is an expression and is not to be confused with the arguments ... in the function(...) call.

No, `(...)` is mandatory in the `if` and is thus not an expression, but inherent syntax of `if`. `...` is the expression. Therefore, unlike languages such as Python where you may write `if ...:`, it does not make sense to write it separately, since the two are inseparable.

But like I said, it is not that big of a deal.

>For example it is perfectly valid C to write if var instead of if (var),

[No it's not.](http://ideone.com/pTpTDi) Besides, this isn't C. ;) -- But it's not valid C++ either.

>The syntactical difference being the parentheses are part of the expression itself in the statement while simply being a notation for arguments in the function call. This is why I often write if (...) and function( ... ).

`function( ... )` makes even less sense. Pretty much everybody writes `function(...)`. I'd kinda hate to see a mathematician write `sin( 3 )` (although thankfully I have not)

**Comment by Djhg2000** [comment]
I stand corrected on omitting the parentheses, hard to imagine I'm getting this rusty on C syntax already.

However I am absolutely sure about having a space between `if` and `(...)`. This applies in many languages and C being the first one in which I learnt to do so.

Separating the arguments in function calls with spaces is a nonstandard habit I picked up after doing a lot of BASH-scripting (where it is required since `(` is a command). It just kind of stuck and I'm not saying this project should use it, but I've found it often improves readability with long/complicated arguments. For things like `sin(3)` I usually omit the spaces because it's obviously very short to begin with.

**Comment by paulsapps** [comment]
if(x) and if (x) both compile.. its just a matter of opinion on which is "better"

**Comment by Djhg2000** [comment]
I just double checked my primary source for C; Kernighan & Ritchie "The C Programming Language". Expressions are indeed supposed to be encapsulated with parentheses but there should also be a space separating the expression. This can first be seen in chapter 1.2 for `while` statements and is then defined specifically for `if` statements in chapter 1.6 (page 23).

I'm siding with the book here.

**Comment by paulsapps** [comment]
I dunno about C but in modern C++ it doesn't matter, even things like std::vector<std::vector<int>> a; compile without spaces now.

**Comment by Djhg2000** [comment]
Call me old school but just because it compiles doesn't mean it's good enough. A lot of thought went into the design of C and there's practically nothing which isn't in there for a good reason.

I'm still siding with the book on this. Again it's ultimately up to the project leaders to decide but this is my opinion.

**Comment by JayFoxRox** [comment]
Linked to #235

**Comment by danhedron** [comment]
#235 is merged. There are [Coding Conventions](https://github.com/rwengine/openrw/wiki/Coding-Conventions) now.
