### ISSUE TITLE
Subtitles overlap each other in the first cutscene

### ISSUE THREAD

**Issue by PureTryOut** [rwengine/openrw#102]
In the very first cutscene, where the girl shoots her boyfriend (forgive me, I don't know their names), when the girl starts talking, the subtitles overlap each other, making me unable to read what it actually says.

![openrw](https://cloud.githubusercontent.com/assets/1565836/15626943/0b67058e-24d4-11e6-85fd-6425465a44de.gif)

**Comment by christooss** [comment]
This is a duplicate of bug #50 https://github.com/rwengine/openrw/issues/50

**Comment by PureTryOut** [comment]
Ooh woops didn't see that one, my bad, closing this one.
