### ISSUE TITLE
0: fatal error:  'AL/al.h' file not found #include <AL/al.h> (Mac)

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#118]
Hi

I want to inform you that I can't compile Openrw on Mac. I installed openal-soft from homebrew, but it didn't work, and I know that Mac has own version of Openal. Can you tell me which version of Openal do you plan to use in this project?

https://gist.github.com/gbudny/9a5d04f74994e7a3ba14d35d34941fba

**Comment by christoph-heiss** [comment]
`openal-soft` is key-only, so you need to link it manuelly using `brew link --force openal-soft`

**Comment by gbudny** [comment]
Thanks.

It works.
