### ISSUE TITLE
Debug camera not used if cutscene / scripted camera active

### ISSUE THREAD

**Issue by JayFoxRox** [rwengine/openrw#128]
During cutscenes the debug camera is not activated. It also won't work if the camera is controlled by the script.
That is a problem because it would be useful to debug those scenes too.
We currently can't look at places where characters and vehicles will be spawned for example.

(It would also be useful if we could unpause the game while the debug menu is opened / debug camera is active. But that's another issue)

**Comment by danhedron** [comment]
Fixed by #252
