### ISSUE TITLE
LoaderTXD: problem loading font textures

### ISSUE THREAD

**Issue by haphzd** [rwengine/openrw#135]
Maybe it's just me and my compiler (or not - #37)  , but only the first texture (_font1_) from _fonts.txd_ gets loaded. Debugger shows that BinaryStreamSection somehow obtains incorrect section header for a second texture despite having correct offset. _pager_ and _font2_ are skipped as result. 
Files are from retail version, sha-1 of _fonts.txd_ `dd62a1eabd0b373f5bc5506285317f7f22297304`

![txdloader2](https://cloud.githubusercontent.com/assets/19692811/15808480/48c7b35e-2b89-11e6-8f33-26108e7456fa.PNG)
Can `reinterpret_cast` misbehave like that (five byte jump from offset)?

**Comment by JayFoxRox** [comment]
Is the data pointer still fine (do data[0] - data[15] look correct etc.)? Was it fine in the first place?
Maybe this is caused by the ambiguity of data and offset (either in CC or in GDB), being both member variables and arguments to that function?

**Comment by paulsapps** [comment]
It can be caused by corruption - maybe something got overwritten. If you run that bit of code in valgrind memcheck it will tell you.

**Comment by haphzd** [comment]
Well, it was a corruption #137

**Comment by danhedron** [comment]
Just to clarify, is this particular issues resolved by #137?

**Comment by haphzd** [comment]
Yes.
