### ISSUE TITLE
Clicking "Resume" on the main menu causes the game to hang when there is no save game

### ISSUE THREAD

**Issue by aaronfranke** [rwengine/openrw#138]
Before clicking "Resume" https://i.imgur.com/aidebfM.png
![1](https://cloud.githubusercontent.com/assets/1646875/15911999/b89c7e34-2d97-11e6-9480-27f3f6f9646d.png)

After clicking "Resume" https://i.imgur.com/QBsbdqt.png
![2](https://cloud.githubusercontent.com/assets/1646875/15912004/be31f0ea-2d97-11e6-8bfb-56fab1517d6d.png)

**Comment by danhedron** [comment]
Resume has been removed.
