### ISSUE TITLE
Man at the beginning is duplicated as a ghost

### ISSUE THREAD

**Issue by aaronfranke** [rwengine/openrw#139]
![3](https://cloud.githubusercontent.com/assets/1646875/15911958/92d37f22-2d97-11e6-801f-916474f87af7.png)
![4](https://cloud.githubusercontent.com/assets/1646875/15911961/947f8b22-2d97-11e6-8299-b1fb76cc014d.png)
![5](https://cloud.githubusercontent.com/assets/1646875/15911963/9791ec74-2d97-11e6-8270-e23f5ebe701b.png)

**Comment by PureTryOut** [comment]
Duplicate of #134
