### ISSUE TITLE
Parked vehicles spawn in ground

### ISSUE THREAD

**Issue by danhedron** [rwengine/openrw#162]
Some vehicles spawned by the traffic system (see PR #159) spawn in the ground.

It's unknown how this should be corrected.
- Does the game ray cast against the ground to place vehicles?
- Do spawned vehicles respect the normal of the surface they spawn on?
- How does the game prevent tall vehicles from clipping into the ground?

**Comment by spaceeinstein** [comment]
Is there a way to determine the base of the model? It sounds like you are placing the vehicles by their center of mass. You could add the distance between the center of mass and the base of the model to the ground z to prevent most clippings.
