### ISSUE TITLE
LoaderCOL should be refactored

### ISSUE THREAD

**Issue by JayFoxRox** [rwengine/openrw#170]
There are a couple of strange + bad things in the COL loader which can cause crashes.
Some of these bugs can be observed using valgrind memcheck.

These might be (one of?) the reason why OpenRW crashes on windows (PR #130).
- [If `head2.numfaces == 0`, then `maxvert = 0`. This loads 1 vertex despite no faces](https://github.com/rwengine/openrw/blob/master/rwengine/src/loaders/LoaderCOL.cpp#L219)
  (This does happen in GTA3)
- [No idea why this is there](https://github.com/rwengine/openrw/blob/master/rwengine/src/loaders/LoaderCOL.cpp#L226)
- [Use number of actual vertices read here?! What if a file is kind of "broken" and contains garbage vertices or bad indices (`maxvert+1` is not `numverts`)?](https://github.com/rwengine/openrw/blob/master/rwengine/src/loaders/LoaderCOL.cpp#L192).
  (Happens in GTA3: `numverts == 174`, `maxvert == 165`; however `maxvert+1 > numverts` does not occur, except in case `numfaces == 0`)
- [Why?](https://github.com/rwengine/openrw/blob/master/rwengine/src/loaders/LoaderCOL.cpp#L194)
- Why are all `version == 1` infos stored in a struct called `CollTHeaderV2` ?

All links / line numbers are for revision cd0a11d899ea1498fc62f7b8989faf289abff4fd

**Comment by paulsapps** [comment]
Btw std::ifstream dfile(file.c_str()); < shouldn't this be loading as binary?

**Comment by darkf** [comment]
>// TODO support version 2 & 3.

IMO these should panic (throw an exception) or at least log that it tried to parse something it couldn't.

@paulsapps Yep, for sure, the difference matters on Windows.

**Comment by danhedron** [comment]
Handled in #245
