### ISSUE TITLE
Builds using MS Visual Studio C++ compiler fail

### ISSUE THREAD

**Issue by JayFoxRox** [rwengine/openrw#173]
This has been reported on irc by PerikiyoXD: http://hastebin.com/vosozulugo.tex (Based on #130 )

Aside from the missing dirent.h (RW_WINDOWS not set) there are some syntax issues too with how we use pointers in templates.

More info appreciated.

**Comment by JayFoxRox** [comment]
Update:

I've been working on this in my branch 'appveyor'. The code quality is horrible and the code will have to go through some iterations.
I'll still try to merge it soon so we can find more developers.

We use some C++11 features not supported in Visual Studio 2013, so we need VS2015 minimum

rwlib: compiles
rwengine: compiles
rwgame: compiles, but linking fails due to not having proper dependencies installed

Tests and tools have not been ported to MSVC yet.

**Comment by ShFil119** [comment]
It should be fixed now.
