### ISSUE TITLE
Windows version crashes before the menu appears

### ISSUE THREAD

**Issue by JayFoxRox** [rwengine/openrw#175]
This is based on #130 .

Reportedly this has been getting worse / affected since the switch from SFML to SDL (during review of #130 ).
It's unclear wether #170 is the sole reason for this.

Static analysis, memory checking at runtime and backtraces of the crash on windows would be appreciated.

(Originally reported by @haphzd via irc and #130 )

**Comment by JayFoxRox** [comment]
@haphzd it seems to work fine for @darkf . Can you test wether the issue still exists for you?

**Comment by haphzd** [comment]
This was related to build environment and/or g++ 4.8.3. Switched to MSYS2 with current packages long since.

**Comment by JayFoxRox** [comment]
I'll close this then.

We should probably run valgrind / asan etc. once in a while to make sure this isn't due to memory layout.
