### ISSUE TITLE
Improve command line argument parsing and add usage

### ISSUE THREAD

**Issue by darkf** [rwengine/openrw#177]
`rwgame --help` should display all available parameters, and it should support both short and long options.

There are some nice libraries for this, such as:

- boost::program_options (http://www.boost.org/doc/libs/1_61_0/doc/html/program_options.html)
- http://tclap.sourceforge.net/
- http://optionparser.sourceforge.net/
- https://github.com/tanakh/cmdline
- http://ezoptionparser.sourceforge.net/

Some of these are a single header file. Can we include one of them in `external/` or as a submodule and use them?

**Comment by JayFoxRox** [comment]
We depend on boost anyway and it's widely available.
I didn't review the other libraries though.

Boost gets my vote.

---

However, this is clearly a low-priority issue as the current system works.

**Comment by danhedron** [comment]
This is done in #229. we can open another issue if we end up removing boost in the future.
