### ISSUE TITLE
Add some screenshots in the README

### ISSUE THREAD

**Issue by neuromancer** [rwengine/openrw#19]
I think adding some screenshots in the README can show the current progress to potential alpha-tester.

**Comment by JayFoxRox** [comment]
The sheer amount of upvotes this has gotten means this should be fixed asap.
I also had people ask me for screenshots on 3 occasions as they had no idea about the state of the project.

Screenshots should include:

- Cutscene
- Ingame walking
- Ingame in car; possibly with debug menu opened (kids gonna love that!)

Those will be attention grabbing. However, we also must make absolutly sure that this project is currently targeting developers interested in GTA and that the gameplay is still non-existent.
We should combine this by linking to a TODO list or the story mission issue; which should include a list of opcodes each mission uses for example.

Slightly offtopic:
We should also find someone to work on art stuff ([or is this logo considered final?](https://avatars0.githubusercontent.com/u/19520421?v=3&s=200)) so we can spread the word / find more developers?

**Comment by tsjost** [comment]
> or is this logo considered final?

Very much not! I threw it together in a few minutes to just have _something_ when we got flooded, for the record.
