### ISSUE TITLE
OpenRW needs a logo

### ISSUE THREAD

**Issue by JayFoxRox** [rwengine/openrw#192]
We should have a logo asap.
- It must be a vector graphic
- Must not contain the project name if it's recognizable
  - Should give us the option to put the name next to it
- It should not contain non-free (as in beer) fonts.
  - (To my understanding, there are free versions/variants of [pricedown](http://www.dafont.com/pricedown.font?text=OpenRW))
- If it includes GTA related material it should target the 3D era of games
- It should not be tied to any specific GTA game
- Shape/Color has not been decided yet, do whatever you feel like
- Different versions of the same style for different purposes are possible
  - It should also be printable in case we ever want to represent the project at events (flyers, banners, ..)
  - Should work as icon (windows executable, android app, ..)
  - Should work as digital banner (website, forum, ..)
- It should not contain any obscenities

Suggestions by the community are welcome.

**Comment by Mischa-Alff** [comment]
This is just a quick mockup but I'm willing to expand on it if you're interested!

![ip28rr7](https://cloud.githubusercontent.com/assets/1387364/17564647/6bd221d4-5f34-11e6-8cc9-ce0ca530c7d4.png)

**Comment by madbad** [comment]
Just some quick sketch to give the "behind idea"... The final version also somewhat remember a sight... that is somewhat related to the gta serie.
![1](https://cloud.githubusercontent.com/assets/1399454/17570210/ccb7b1a0-5f4b-11e6-9b2a-c33123fe631b.png)Open
![2](https://cloud.githubusercontent.com/assets/1399454/17570213/cdfd06be-5f4b-11e6-8f6e-7db1645a2a57.png)Re
![3](https://cloud.githubusercontent.com/assets/1399454/17570216/d0784200-5f4b-11e6-9283-d1027f543597.png)Write

**Comment by kwadroke** [comment]
A quick draft of a logo I originally used with the pricedown font (since removed) ![openrw_new](https://cloud.githubusercontent.com/assets/3247032/17611327/e9b1e526-600b-11e6-8e52-9bf0d9f1e283.png)

**Comment by vflyson** [comment]
What about a recycling sign with a crosshair inside of it or a car wheel inside of a crosshair?
Perhaps a turbo? A steering wheel?

**Comment by JayFoxRox** [comment]
@madbad I appreciate the fast feedback. Sorry for not responding earlier.
In my opinion your logo idea looks too much like the VW logo or a peace symbol. Even with a different font / color scheme it would be extremly hard to see the ORW.
I don't think it really resembles a sight either - however, I like the idea of using a sight as a possible option.

---

I've planned to do something but didn't find time for it yet. I had a couple of ideas.
One was to reuse the weapon hud-style as it remained largely unchanged between games, possibly containing on open box with "OpenRW" or just "RW" written on it or something.

I was also going to look into extending the idea by @kwadroke . However, reducing it to just the background without text - probably makes a create favicon etc.

Another idea I had was to use the auto-aim symbols from each game (meaning ring-parts or 3 arrows, possibly spinning in an animated version of the logo), however, I ditched that idea as it might not be the most recognizable to PC players.

So you can see a pattern here which I tried to use: Parts which remained mostly unchanged between GTAs (GTA3, VC, SA; possibly LCS, VCS)
- Weapon HUD / Radar
- Some cars such as Admiral
- Box art, stencil style intro movie
- "Mission passed" texts and mission task texts
- Game artwork / loading screens
- Character idle stance
- Pricedown Logo

**Comment by leilei-** [comment]
I would probably just drop lettering altogether and make a simple hand opening a car's door handle.

**Comment by danhedron** [comment]
I made an attempt at the broken mosaic style, using colours that are relevant to the games.
![logo_box](https://cloud.githubusercontent.com/assets/418211/18331866/e56a9e96-7559-11e6-8027-e3ed54b68f3f.png)

**Comment by PerikiyoXD** [comment]
A quick thing

![drawing](https://cloud.githubusercontent.com/assets/3116368/18375495/0d4fc4b0-7657-11e6-9dc8-a7f5344bcdf3.png)

**Comment by JayFoxRox** [comment]
I personally still think (all) the current proposals are too complicated / colorful.
However, I like the @PerikiyoXD color scheme better, but the general shape + font color of @danhedron was better.

**Comment by LavenderMoon** [comment]
Something like this?

![openrw logo merged mockup 3](https://cloud.githubusercontent.com/assets/12167542/18386040/31af8a92-7662-11e6-847c-3aa1bb4c33dc.png)

**Comment by danhedron** [comment]
![logo_box](https://cloud.githubusercontent.com/assets/418211/18403794/d3e29328-76de-11e6-8936-d549e5d71b6a.png) ![logo_box_small](https://cloud.githubusercontent.com/assets/418211/18403795/d5572868-76de-11e6-92b7-16533b16573b.png) ![logo_box_favicon](https://cloud.githubusercontent.com/assets/418211/18403841/0f1fcc26-76df-11e6-99d9-89f822e40b59.png)

Smaller sizes might need the text to change a little.

**Comment by ClaudeLib** [comment]
Here's something I made a while back, for an [entirely different OpenRW](http://gtaforums.com/topic/810161-rel-openrw/), slightly revised.
![en06b7o8](https://cloud.githubusercontent.com/assets/5920490/21835474/17989872-d7df-11e6-83d2-9abd31f52134.png)
Sorry for non-vector, but if you like it, I'll redo it in Inkscape.

**Comment by danhedron** [comment]
We'll use the coloured gradient version of the logo for now. Since it's pretty legible at most sizes.
