### ISSUE TITLE
OpenRW needs a website

### ISSUE THREAD

**Issue by JayFoxRox** [rwengine/openrw#193]
When we get linked to, we should have a website to separate users (forward to reddit) from developers (forward to github). It should also serve as a central part of our ecosystem.

A simple splash screen is enough for now. This depends on #192 but a placeholder could be used.

Optional features:
- Blog or something? (Preferrably something simple + markdown?)
- Media gallery (imgur integration?)
  Required:
- Link to GitHub
- Link to Reddit as forums
- IRC address/channel name (+ Link to IRC webchat)
- Link to youtube channel if applicable (we don't have one yet)

More content will be added in the future

It's probably a good idea to re-use the content available on the github wiki page as data source.
As a custom forum etc means much maintenance we should use reddit which brings us a lot of users who stumble to our subreddit by accident + it's a nice thread forum (we need some reddit css champion though?).

Ideally the homepage would be open source and be easy to host (github pages? idk anything about webdesign)

Note: We already have a domain.

**Comment by Calinou** [comment]
I could help on this, I have some experience with working with static site generators such as Jekyll. I've worked on sites like [Minetest](http://minetest.net) (uses Jekyll) or [Godot Engine](https://godotengine.org/) (uses October CMS).

I've also gotten OpenRW to run successfully on Linux, so I can take screenshots and videos as needed.

**Comment by JayFoxRox** [comment]
http://openrw.org/ is now pointing at a preliminary page.
I'm not sure what happens to http://openrw.se/ @tsjost ?

**Comment by danhedron** [comment]
I've pushed a new site created by @Calinou to the http://openrw.org github pages site.
