### ISSUE TITLE
Project structure - Who is developing OpenRW?

### ISSUE THREAD

**Issue by JayFoxRox** [rwengine/openrw#199]
https://github.com/rwengine/openrw/blob/master/CONTRIBUTING.md#evaluating-pull-requests reads that the PR must be reviewed by "members of the organization". That is very vague because the rwengine organization has no publicly visible members.
It also makes people think that there is a closed group of developers.

I’d personally vote for explicitly stating that OpenRW is a community project and that there is no “team”. All instances of “organization” etc. should be replaced by “active contributors” or “past contributors” and we should also inform people that by being active contributors they’ll gain moderating permissions for reddit and the repo.

This is not limited to the CONTRIBUTING.md, but also applies to README.md and all other docs such as wiki.

**Comment by JayFoxRox** [comment]
Related to #204 which fixes part of the problem.
I'd like to keep this opened for a couple of days so we can also README, review the wiki etc.

**Comment by JayFoxRox** [comment]
Update: I've looked around our files now.

* [ ] README should make it more clear that we accept contributions
* [ ] The wiki Contributing page would mostly be static and it's better to pack it with the source code. We should hence merge the remaining Contributing wiki page with the CONTRIBUTING.md
* [ ] "Do you accept contributions?" in the FAQ should link to the CONTRIBUTING.md
* [ ] "Development" wiki page should link to the CONTRIBUTING.md near the header to redirect people
* [ ] "Editing OpenRW" on "Getting Started" wiki page should be renamed to something which screams "Developing" or "Contributing".
* [ ] "Reporting Issues" is essentially the same as the stuff in CONTRIBUTING.md and should be included in source and binary packages.

We can also flip this around and make CONTRIBUTING.md very slim and link to the wiki instead. (Which might be more sane as we can easily upgrade the wiki in case someone decides to host ancient releases.. - I only realized this after writing the above)

**Comment by danhedron** [comment]
+1 on contributing linking to the wiki.

We need guidance on how to review PRs too, what constitutes accepting (just saying it works doesn't convey that you are +1ing the PR), how should changes that could break on different platforms should be reviewed (including a new header for example).

**Comment by JayFoxRox** [comment]
Most of this was fixed in #213.

We should eventually have a sitemap for the wiki to keep track of all the links too btw, but those are all worth separate issues (are there tools for that?).
