### ISSUE TITLE
Test organisation is a mess

### ISSUE THREAD

**Issue by danhedron** [rwengine/openrw#2]
Tests are currently split between the tests directory, and rwengine/tests.

Tests should be organised into folder of the component they are for:
- rwgame/tests
- rwcore/tests
- rwengine/tests

etc.

**Comment by JayFoxRox** [comment]
Update:

I can't see rwengine/tests/ anymore. However, all tests have been moved to tests/ now (meaning they are not part of their respective component)

**Comment by ShFil119** [comment]
Is this still valid?

**Comment by danhedron** [comment]
Too vague. Will action specific issues with tests by dependency on game data, component focus etc.
