### ISSUE TITLE
Add some comment on the status to the FAQ/readme

### ISSUE THREAD

**Issue by gsnedders** [rwengine/openrw#212]
I'd love to know how complete and how working the project is from looking at the (AFAIK only) home page, especially without having to click through to the FAQ. Consider questions such as:

- Can I play the game at all? (Screenshots suggest yes!)
- Can I play the game at a reasonable framerate at all? (On most modern hardware, even if not on that which the original closed-source binary ran on.)
- Can I play the whole game?
- Can I play the whole game at a reasonable framerate?
- Can I play the game as I would the original closed-source binary, or does it have issues I should be aware of?

**Comment by JayFoxRox** [comment]
I've tried to address some of this on the FAQ now.

* **Can I play the game at all? (Screenshots suggest yes!)**
I guess this is implicitly answered?

* **~~Can I play the game at a reasonable framerate at all? (On most modern hardware, even if not on that which the original closed-source binary ran on.)~~**
"No idea", added this to the FAQ.

* **~~Can I play the whole game?~~**
Check mission tracker, added to FAQ.

* **~~Can I play the whole game at a reasonable framerate?~~**
"No idea", added this to the FAQ.

* **Can I play the game as I would the original closed-source binary, or does it have issues I should be aware of?**
Really hard to answer, but obviously we are still in development, the mission tracker suggests that, the screenshots contain obvious problems. We could possibly add a recommendation that people who only intend to play the game should instead use something like "Wine" or run the game on natively supported platforms.

I believe adding this info to the README adds a lot of noise in the PRs (as we'd constantly have to remind people to improve the README). It also links to the FAQ and gives a good overview of the project.
I think the issues reflect the current status very well, and the wiki is an extension of that.

**Comment by gsnedders** [comment]
Thanks!
