### ISSUE TITLE
Occasional crash in taxi sub-missions

### ISSUE THREAD

**Issue by danhedron** [rwengine/openrw#223]
Repeatedly starting and stopping the taxi sub-mission seems to cause a crash in `opcode_00db` where the character is null.

Should 00db be able to withstand a nullptr? why does the script pass an invalid handle to this opcode?

**Comment by husho** [comment]
Invalid ped handle is checked by the scm script using `0118 IS_CHAR_DEAD` opcode, the problem was that it returned false instead of true when ped didn't even exist.

**Comment by husho** [comment]
Fixed by #443.
