### ISSUE TITLE
Debian Sid dependencies and build fail when following Ubuntu build guide

### ISSUE THREAD

**Issue by TacoDeBoss** [rwengine/openrw#228]
When using the Ubuntu dependencies from the Building section of the wiki on a Debian Sid system, dependencies will fail as libboost-dev is 1.61, and libboost-filesystem1.58-dev and libboost-system1.58-dev are listed in the wiki. These are not compatible with each other, and thus can't be installed at the same time. Build will fail without these packages.

This is easily fixed by installing libboost-system-dev and libboost-filesystem-dev from the Debian Sid repositories, as these are 1.61 versions and work perfectly in place of 1.58 versions. I suggest replacing the 1.58 packages listed with the regular *-dev versions listed here, as these should match with each other on all systems.

**Comment by JayFoxRox** [comment]
The wiki should be editable by you, feel free to make the appropriate changes.
If you don't have the necessary permissions you can report this here. Please also suggest the exact package names / line we should be using in the wiki.
Thanks!

**Comment by TacoDeBoss** [comment]
I simply replaced the package names in the wiki `libboost-filesystem1.58-dev` and `libboost-system1.58-dev`  with `libboost-filesystem-dev` and `libboost-system-dev`.

I checked the repositories for both distros and different releases, and this should work on Ubuntu and Debian all the same, without introducing any compatibility conflicts.
