### ISSUE TITLE
Make more liberal use of smart pointers

### ISSUE THREAD

**Issue by darkf** [rwengine/openrw#239]
The codebase is quite spaghetti at some points and there are countless memory leaks just from allocating pointers and never freeing them (most don't even have destructors :|)

`std::unique_ptr` and `std::shared_ptr` should be sprinkled pretty heavily around.

**Comment by danhedron** [comment]
In rwgame there are a few things in particular that need to have their lifetimes managed:

- State instances
- some members of RWGame should either be made uniqure_ptrs or just member variables

If you see anything else that's dubious (i.e. a raw new or delete) please leave a note so it's possible to track what needs fixing.

**Comment by danhedron** [comment]
Some more thoughts:
- Activities
   - These should just be stored as a union/variant anyway, doesn't need dynamic allocation
- Bullet shapes / Collision Model
   - I will be changing collision stuff soon so I'll take care of these pointers
- SCMFile
    - Probably doesn't need to be dynamically allocated, RVO and move semantics should be enough. Should use unique_ptr internally
- IDE objects
    - Affected by changes in [upcoming PR](https://github.com/danhedron/openrw/pull/13).
- Animation / Skeletons
   - Highly likely to be affected or deleted with librw

**Comment by JayFoxRox** [comment]
Was this handled in #244 ?

**Comment by danhedron** [comment]
Partially. There's lots more to do (some incoming).

**Comment by danhedron** [comment]
This issue is rather vague and more work has been done in this area.
