### ISSUE TITLE
Use emscripten to compile OpenRW for the web

### ISSUE THREAD

**Issue by marco-c** [rwengine/openrw#24]
It would be really nice to play GTA III in the browser!
Planning it from the start might be easier than doing it later.

**Comment by danhedron** [comment]
There are some limitations with emscripten that haven't been taken into account in the design of OpenRW. I'm not sure how the game could ready data from the hard disk either. I'll leave this open if someone wants to look into what needs to be done to even make this possible.

**Comment by marco-c** [comment]
> I'm not sure how the game could ready data from the hard disk either.

It should be possible, you can let the user select the file from their filesystem and then you can store it in the Emscripten FS.

Some docs: https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications.

**Comment by JayFoxRox** [comment]
I think this should happen in a fork and as such, this issue should be closed.
There is no gain in planning with this in mind. It would only hinder development.
We don't know how good emscripten etc. are in 5 years anyway (when OpenRW might be useful).

---

Eventually there'll be ton of actual game related bugs / issues. So we should prepare by outsourcing issues (We are at 62 open issues ~ 3 pages worth of issues.). Especially these "enhancement" issues which are only possible once the core elements are complete. (~ 5 years as mentioned above, seems like a fair estimate to me; do you really want to keep the issue opened for 5 years?)
We could also collect ideas like this on a wiki page and link to the closed issues.

**Comment by JayFoxRox** [comment]
This is an emscription issue, not OpenRW.
If you want to maintain an emscripten version of OpenRW fork the project or make emscripten work with anything you throw at it.
We won't support this officially for a looonnnggg time.

I'll close this now due to the reasons I listed earlier.
