### ISSUE TITLE
OpenRW doesn't compile on MSYS

### ISSUE THREAD

**Issue by Matriks404** [rwengine/openrw#255]
There is an cmake error:
`CMake Error: Could not create named generator MSYS Makefiles`

I am using msys2-x86_64-20161025.exe from the link on the "Building" article on Wiki, and everything was setup like described.

**Comment by hcorion** [comment]
I believe you want to use Unix Makefiles.

**Comment by Matriks404** [comment]
I don't know what happened, but it seems that it is fixed
