### ISSUE TITLE
Can't enter Speeder vehicle

### ISSUE THREAD

**Issue by hcorion** [rwengine/openrw#274]
When I try to spawn the speeder vehicle from the debug menu (M key) the game crashes with a segmentation fault:
```
openrw/rwengine/src/objects/VehicleObject.cpp:162: Vehicle has no chassis_dummy
[1]    16469 segmentation fault (core dumped)  rwgame
```
Game build d8cda626

**Comment by JayFoxRox** [comment]
Yes, boats (not limited to speeder) are currently broken.
They used to work at some point (I believe) but have been broken for a long time. There is no point in finding the regression either.

(Focus is on mission scripting, using a more accurate renderer and generally adding more features which are required early on)

**Comment by dracc** [comment]
Somewhat related, the Columbian (a big pickup truck) gives segfault.

> 0x000055555592f440 in VehicleInfo::{unnamed type#1}::operator[](unsigned long) const (this=0x5555563330d8, index=0)
>    at /home/dracc/Public/openrw/rwengine/src/objects/VehicleInfo.hpp:98
>98	            return back[index];

**Comment by dracc** [comment]
It seems the Columbian issue was related, as entering it works now. 👍
