### ISSUE TITLE
Windows MSYS build process doesn't generate DLLs

### ISSUE THREAD

**Issue by JarnoVgr** [rwengine/openrw#278]
I've followed the building instructions for Windows MSYS (as stated on the Wiki) on Windows 10 x64. Building goes fine and rwgame.exe gets generated. However, when launching it, it requires DLLs such as:
- libBulletCollision.dll
- libboost_filesystem-mt.dll
- libboost_system-mt.dll
- libboost_program_options-mt.dll
- libBulletDynamics.dll

These are supposed to be generated by the compiler/linker, right? Or is it required to download this dependencies from an external source?

**Comment by JarnoVgr** [comment]
My mistake of course. The DLLs were placed in MSYS system directories.

For anyone else coming accross this issue: Just launch the executable from the MSYS console/terminal:
`./rwgame/rwgame.exe`

**Comment by haphzd** [comment]
MSYS binaries folder is supposed to be in system PATH variable, then you can launch rwgame outside of the environment .
