### ISSUE TITLE
The Mac version

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#28]
Hi

Can I run this game on Mac?

**Comment by TacoDeBoss** [comment]
From the FAQ:

Does OpenRW work on Windows/Mac/WebGL/BSD/Android/iOS/Raspberry Pi/something?

No idea. Please let us know!

**Comment by JayFoxRox** [comment]
So.. did this work?

**Comment by JayFoxRox** [comment]
Just looked for this myself.
Closed because #63 replaces this.
