### ISSUE TITLE
Only give in-car perks to player characters

### ISSUE THREAD

**Issue by vflyson** [rwengine/openrw#281]
Currently, all characters (including NPCs / AI) will receive in-car perks.
The goal of this issue is to make sure that non-player characters would not receive any in-car perks.

This might also be necessary for other events / functions.
Hence, a `CharacterObject::isPlayer()` should be implemented to make it easier to limit these player-only events to players.

//Edit: renamed and edited by JayFoxRox with permission by @vflyson

**Comment by JayFoxRox** [comment]
These are 2 seperate issues really: One about a convenience function in code, the other one about a gameplay feature being wrong.

In my opinion this issue should be renamed to reflect the wrong behaviour of in-car perks.

That way a user can see the issue directly from the title list (which is also easier to find with a search). Convenience functions are something which can just be added as you work on an issue unless it's a highly debatable subject / useless helper function.

**Comment by danhedron** [comment]
I believe this was fixed with #289, closing
