### ISSUE TITLE
OpenGL dependency???

### ISSUE THREAD

**Issue by polyzium** [rwengine/openrw#284]
```
$ cmake .. -G"MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release
CMake Error at C:/msys64/mingw64/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY)
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/msys64/mingw64/share/cmake-3.7/Modules/FindOpenGL.cmake:162 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:86 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/Polyzium/openrw/build/CMakeFiles/CMakeOutput.log".
```
I suffer for 40 minutes now trying to build OpenRW... help me pls

**Comment by JayFoxRox** [comment]
Did you figure this out yet? Can you post the solution here if it's already solved?
(I believe you asked on IRC too - did that help?)

**Comment by polyzium** [comment]
Nah i didn't solve it yet

**Comment by pafmaf** [comment]
Can you try installing the 32bit dependencies as well and re-generate the project?

**Comment by hcorion** [comment]
I'm on Linux now, but from what I can remember from building on windows, I think you need to build it using MINGW makefiles, not Msys.

**Comment by darkf** [comment]
@polyzium Is this still an issue when building fresh?
