### ISSUE TITLE
World is initialized two times

### ISSUE THREAD

**Issue by aldoxtor** [rwengine/openrw#292]
When I used keyboard to navigate in menu the world is initialized two times.
http://imgur.com/a/Ifn91

**Comment by JayFoxRox** [comment]
When the mouse is used this doesn't happen?

Does this only happen in test mode and main menu, or also in the debug menu (press <kbd>M</kbd> during gameplay iirc) or for the savegame loads / campaign?

**Comment by JayFoxRox** [comment]
Why was this closed?

**Comment by ShFil119** [comment]
I assume:
https://github.com/rwengine/openrw/commit/887e0333c874fd71d1fc15a288f02e0cacc05eaf

**Comment by danhedron** [comment]
I thought GitHub was supposed to link to the closing commit…
