### ISSUE TITLE
Issues when running openrw above or below 30fps

### ISSUE THREAD

**Issue by SonofUgly** [rwengine/openrw#297]
When running at 60fps all moving objects shudder back and forth. It gets more noticeable the faster you're moving. Example video (make sure to watch in 720p60): [Youtube](https://youtu.be/m87bJxE9hnU?t=613)
This also happens when running at 15fps.

This seems to be because [GAME_TIMESTEP](https://github.com/rwengine/openrw/blob/master/rwgame/game.hpp#L17) is locked to 30fps, as setting it to 1/60 fixes the issue when running at 60fps, and 1/15 fixes 15fps (but makes the physics buggy - cars constantly bounce up and down).
Also, when running the game below GAME_TIMESTEP the game will run in slowmo - so halfspeed when running at 15fps when it's set to 1/30, and 30fps at 1/60, or a quarterspeed when running 15fps at 1/60.

**Comment by theo546** [comment]
I can feel this when Claude is running too!

**Comment by danhedron** [comment]
Previously, all objects were interpolated regardless of whether they were capable of moving. I had removed this with the intention of replacing it with the bullet motion state interpolation and manually interpolating everything else that actually moved. However I haven't been able to make time for this, but interpolation of motion states would help a lot.

**Comment by kargaroc** [comment]
I have a 144hz monitor, and at the default settings the game is unplayable from the stutter.  I'll try the workaround for now (not that I actually play that often but it's a fun enough toy), but I'm looking forward to what you have in store.

**Comment by danhedron** [comment]
#309 is now merged, this should be better now.
