### ISSUE TITLE
Core functionality should live in a core module

### ISSUE THREAD

**Issue by danhedron** [rwengine/openrw#3]
The following things could be moved from rwengine:

* Everything in rwengine/{src,include}/core

**Comment by danhedron** [comment]
rwlib now exists to serve as the location for low level things like the file data structures and platform details. rwengine can now just be for implementing the bulk of the logic for and rendering.

**Comment by JayFoxRox** [comment]
The structure should be improved in the future, but I don't think this issue is very descriptive.
We should probably create a new issue with better title, proposed organization and then follow it with a discussion about the new structure.

Looks like we'll have the clang-format mess all over again.
