### ISSUE TITLE
Replace boost::filesystem with std::filesystem

### ISSUE THREAD

**Issue by darkf** [rwengine/openrw#317]
A post-C++14 TS and now standard in C++17 adds `std::experimental::filesystem::v1` and `std::filesystem` respectively, which is basically `boost::filesystem`.

As Boost is large and a nonstandard dependency, we'd like to move as much of its use as possible to the STL, so this would be a good change to start with.

Since we should target effectively modern compilers, I wager most systems would have this library already -- although we can `#ifdef` it to use Boost as a fallback.

**Comment by danhedron** [comment]
The usual pattern seems to be defining a fs namespace that aliases either the std filesystem or boost filesystem in a header, limiting the checking to a single definition. It should be simple to replace the existing usage
