### ISSUE TITLE
Jumping broken on newer version of bullet?

### ISSUE THREAD

**Issue by ShFil119** [rwengine/openrw#318]
I'm using Arch linux with bullet 2.86-2, charecter's jump is working 50% of all attempts. Rather screen'll become gray, or character will stuck in air or he moves only horizontally.

After testing:
Bullet is culprit, 2.81 Ok
Using newer(2.86, 2.85) results in error. 

Valgrind screams about uninitialized variable.
https://gist.github.com/ShFil119/48f4817491fa2a0f2e34e286360af6cc

Can you share your results with using newer bullet library? Thanks. 
I'll try build bullet on my own and test other bullet version 2.82-2.84.

**Comment by christoph-heiss** [comment]
Can confirm this bug with bullet version 2.86.1 on macOS.
Sometimes just starting to sprint is enough to trigger a crash.

bullet 2.82 works fine.

**Comment by danhedron** [comment]
Can you track down the source of the uninitialized variable with valgrind?

**Comment by ShFil119** [comment]
Nope, btKinematicCharacterController is used as in the examples. Ofc I could miss something. Or examples are outdated.
I was thinking about opcodes, but earlier bullet solves problem.

I suspect corrupted bullet's binary, or bullet internal bug.
