### ISSUE TITLE
Player consistently attempts to enter moving vehicles

### ISSUE THREAD

**Issue by TacoDeBoss** [rwengine/openrw#32]
After causing a self-driving car as explained in issue #31 ,pressing the enter vehicle button results in the player following the car regardless of distance or any movement keys pressed.

**Comment by PureTryOut** [comment]
Not reproducable here. The car kept moving, but when pressing the enter vehicle key again didn't do anything.

**Comment by TacoDeBoss** [comment]
It happens for me when I get out of the car and immediately try to get back in. The car drives away and the player follows the car and can't back out of the "Entering Vehicle" player status.

**Comment by PureTryOut** [comment]
The "immediately" bit did it, can reproduce now.

**Comment by PureTryOut** [comment]
Isn't this fixed by https://github.com/rwengine/openrw/commit/0d2e34ab584625d138ab9afe45546388f22c15e8?
