### ISSUE TITLE
Crash, dereferencing null ptr

### ISSUE THREAD

**Issue by ShFil119** [rwengine/openrw#336]
Dereferencing ScriptObjectType with null instance CharacterObject
It refers to debugging overload from file ScriptTypes.hpp, which catch reason of crash.
Problem:
Game crashes by doing derefence null ptr.
How to reproduce:
After cut scene, jump from the bridge, head towards the parking with a track, go under the bridge. You also can try to return to top of bridge. Result will be the same.
Culprit: opcode opcode_01c2
Log: https://gist.github.com/ShFil119/05ec8ccd8448fee25c4156169c6b2f40

**Comment by ShFil119** [comment]
Script is trying to remove all unneeded pedestrians not visible on screen, so easiest way is to don't remove them. Or add some script which takes care about needed objects/pedestrians.

**Comment by husho** [comment]
This is intended behavior, no need to add scripts or anything (don't really understand what you mean by that), I added nullptr checks just like in original game, so it should be fine now.

**Comment by husho** [comment]
IIRC, fixed by #437.

**Comment by dracc** [comment]
Can confirm, this issue is fixed with #437.
