### ISSUE TITLE
Build in MacOS doesn't work

### ISSUE THREAD

**Issue by aldoxtor** [rwengine/openrw#343]
After recently commits building in Mac doesn't work. I receive this error after compilation:
`[ 97%] Building CXX object rwgame/CMakeFiles/rwgame.dir/states/BenchmarkState.cpp.o
[ 98%] Building CXX object rwgame/CMakeFiles/rwgame.dir/DrawUI.cpp.o
[100%] Linking CXX executable rwgame
ld: can't map file, errno=22 file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [rwgame/rwgame] Error 1
make[2]: *** [rwgame/CMakeFiles/rwgame.dir/all] Error 2
make[1]: *** [rwgame/CMakeFiles/rwgame.dir/rule] Error 2
make: *** [rwgame] Error 2`

Any ideas?

**Comment by ShFil119** [comment]
What's your version of cmake?

**Comment by madebr** [comment]
See [my comment on PR354](https://github.com/rwengine/openrw/pull/354#issuecomment-351715167)

**Comment by christoph-heiss** [comment]
FYI, this issue was fixed by 66b576dcee2abdabd12d1c103669f6f292c6dacb (#358).
