### ISSUE TITLE
Missing texture at street turn next to starting position

### ISSUE THREAD

**Issue by madebr** [rwengine/openrw#352]
This happens at a street turn next to the starting position of the game.

When the house (inside the turn) is out of view, the texture disappears.
At the same time, the street turn becomes transparent. The bottom becomes visible.

![Missing texture at street turn 1](https://user-images.githubusercontent.com/4138939/33146801-ebb6904e-cfc5-11e7-9bbf-3632db70b251.png)
![Missing texture at street turn 2](https://user-images.githubusercontent.com/4138939/33146803-ecf76906-cfc5-11e7-8e39-0422e475a4e1.png)

The texture shows and hides itself, depending of the camera angle.

**Comment by danhedron** [comment]
I think this This is the same issue as #75 , a few objects are culled incorrectly.
