### ISSUE TITLE
Travis builds tests twice

### ISSUE THREAD

**Issue by ShFil119** [rwengine/openrw#355]
For example:
https://travis-ci.org/rwengine/openrw/builds/299359325?utm_source=github_status&utm_medium=notification

**Comment by madebr** [comment]
The current behavior is to build OpenRW twice. One time with `TESTS_NODATA=0` and the second time with `TESTS_NODATA=1`. That way more code paths in the test binary are compiled (but not tested).

We only run the self-test on Travis with `TESTS_NODATA=0`.

Ideally, we should compile once and run only the tests that need no data.

**Comment by madebr** [comment]
I have a branch [no_without_data](https://github.com/madebr/openrw/tree/no_without_data) that removes the `TESTS_NODATA` cmake configuration option.

It requires boost 1.68.0 because of a bug: boostorg/test#153

**Comment by ShFil119** [comment]
Fixed by #693.
