### ISSUE TITLE
Cmake 3.10 fails

### ISSUE THREAD

**Issue by ShFil119** [rwengine/openrw#356]
Log: https://gist.github.com/ShFil119/bbbc676d27c06d25582df7ceb62c22bb

**Comment by danhedron** [comment]
Looks like the new OpenGL CMake package is providing the imported target. The FindOpenGL.cmake module within the repository should check for the ``OpenGL::OpenGL`` target already existing with ``if (TARGET OpenGL::OpenGL)``.  [if docs](https://cmake.org/cmake/help/v3.0/command/if.html).

**Comment by ShFil119** [comment]
Resolved by #358.
