### ISSUE TITLE
Travis MacOS builds

### ISSUE THREAD

**Issue by madebr** [rwengine/openrw#360]
I've been trying to get Travis to build and test on MacOS without complete success.
Since I don't have access to a physical Mac, I don't know how to fix it.

* [This branch](https://github.com/madebr/openrw/tree/macos) contains the basic cruft to get MacOS builds on Travis going ([Travis log](https://travis-ci.org/madebr/openrw/jobs/318225814)).
* [This branch](https://github.com/madebr/openrw/tree/macos_unknown) contains an extra (bad) patch to get the MacOS builds proceed further ([Travis log](https://travis-ci.org/madebr/openrw/jobs/318225992))

The goal is to build OpenRW on MacOS X the same way as we do on Linux (using brew instead of apt-get).

I hope people with actual Apple hardware can solve this. (@aldoxtor @christoph-heiss )

Related: #343 and #354

**Comment by aldoxtor** [comment]
It looks like the last PR fix building on macOS.

**Comment by danhedron** [comment]
Travis is now building macOS.
