### ISSUE TITLE
inline const directory_iterator& begin(const directory_iterator& iter) { (Ubuntu 16.04)

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#373]
Hi

I would like to inform you that I can not compile the last version of Openrw:

https://gist.github.com/anonymous/c369bb37aa02c115ac506d32533e566f

Can you help me?

Grzegorz Budny

**Comment by ShFil119** [comment]
What's your version of boost?

**Comment by gbudny** [comment]
libboost-dev is already the newest version (1.58.0.1ubuntu1).
libboost-program-options-dev is already the newest version (1.58.0.1ubuntu1).
libboost-filesystem-dev is already the newest version (1.58.0.1ubuntu1).
libboost-system-dev is already the newest version (1.58.0.1ubuntu1).

I downloaded Openrw from the master branch.

**Comment by danhedron** [comment]
Looks like filesystem.hpp is missing an include for boost's version.hpp so the shim for older versions is getting defined.
