### ISSUE TITLE
Set $USERPROFILE/Documents as alternative for HOME

### ISSUE THREAD

**Issue by Florin9doi** [rwengine/openrw#375]
Now is required to use: 
`HOME=$USERPROFILE/Documents` (msys) or `HOME=%USERPROFILE%/Documents` (cmd)

**Comment by Spiffyk** [comment]
Is it actually a good idea to put it in `Documents`? Wouldn't it be better to put such files in `AppData` or `My Games`?

In my opinion, `Documents` is a directory designated for user-created files. I do know older games used to put their files in there but I think it's bad practice, as there are much more fitting directories.

**Comment by danhedron** [comment]
Since openrw currently doesn't support saving, loading from the existing directory is the most sensible behaviour.

In future we can save openrw data to a more appropriate location and treat the ``Documents`` path as a read only compatibility option.
