### ISSUE TITLE
Cutscenes not being rendered on MacOS

### ISSUE THREAD

**Issue by emilisb** [rwengine/openrw#378]
I get this on MacOS 10.13.2. I can't do anything until a cutscene ends. The sound is working. I can't skip a cutscene either.

<img width="801" alt="screen shot 2018-01-29 at 23 40 49" src="https://user-images.githubusercontent.com/13116854/35535977-12829a0c-054e-11e8-8883-7d369a698ecb.png">

**Comment by dracc** [comment]
Is this still the same? I had something similar until #385 was fixed, might be related.

**Comment by CliffsDover** [comment]
Yes, still the same with current master 6f50fa.

**Comment by emilisb** [comment]
LoaderCutsceneDAT is not working properly on MacOS. I'm making a PR with a fix soon.
<img width="801" alt="screen shot 2018-06-08 at 19 31 34" src="https://user-images.githubusercontent.com/13116854/41169856-e6cf6564-6b52-11e8-882a-9dbef849ecbb.png">
