### ISSUE TITLE
Detachable parts of nearby vehicles disappear near the edge of the screen

### ISSUE THREAD

**Issue by vflyson** [rwengine/openrw#383]
The issue happens within the latest build (`e3e3642ec2b8085e277cfb0c6d8593178f272af4`)

None of the vehicles on the snapshot below were boarded by the player character.

The missing doors/hoods/trunks get "attached" back to the vehicle when the camera changes the angle and has the detachable part farther away from the edge of the screen.

![openrw_disappearing_door_bug](https://user-images.githubusercontent.com/1392048/35780016-eba4dbc0-09a3-11e8-85d2-0ff7faf9600e.png)

**Comment by SonofUgly** [comment]
Possibly the same issue as #75 & #352? Also noticed this building on the left gets culled when near the edge of screen:
![](https://i.imgur.com/cKR2Ex0.png)
And a similar thing with water:
![](https://i.imgur.com/nbVj5cj.png)

**Comment by danhedron** [comment]
These are all related issues, with the exception of the water.
