### ISSUE TITLE
Broken compatibility with libglm-dev >= 0.9.9

### ISSUE THREAD

**Issue by dracc** [rwengine/openrw#385]
libglm version 0.9.9 or greater breaks the game, menu background is black, most of the game is black (with occasional gray stripes). [Menu](http://i.imgur.com/ubRs4xv.png) [In-game](http://i.imgur.com/fR08hoy.png)
This seems to be due to glm removing default initialization of its data types.

Also worth noting that compilation requires the flag GLM_ENABLE_EXPERIMENTAL.

**Comment by danhedron** [comment]
This should be fixed now.
