### ISSUE TITLE
Could not create GL context: GLXBadFBConfig

### ISSUE THREAD

**Issue by balanicamario** [rwengine/openrw#399]
HI! I want to run OpenRW on a Raspberry Pi3 but I get this error:

I [Game] Build: cf5c75e5
libGL error: MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
E [exception] SDL_GL_CreateContext failed: Could not create GL context: GLXBadFBConfig

What should I do?

**Comment by danhedron** [comment]
OpenRW doesn't support RPI (see #282).
