### ISSUE TITLE
Hunter in OpenRW - CMake driven cross-platform package manager

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#405]
Hi

Do you plan to use Hunter in OpenRW?

https://github.com/ruslo/hunter

Grzegorz Budny

**Comment by JayFoxRox** [comment]
If there is enough support for this tool  and enough motivation to add it: sure, why not.

I'd just recommend avoiding to add hip-solutions which might stop working in a year or two.
Especially package managing is one of the reasons why we have so many linux distros. It's very hard to convince people to settle on the same standards, and likely we'll have linux package managers for decades to come.

msys and vcpkg are okay tools to handle package management on Windows, mac has homebrew as defacto standard, and linux has its own set of package managers.

I generally call the whole package management discussion a first-world problem.
Developers will easily find the package if you just give them a name or website, and users don't have to deal with it anyway if you package your own software probably (which also still has to happen in some form).

**Comment by JayFoxRox** [comment]
Why was this closed?
