### ISSUE TITLE
Replacing char based variables with int?

### ISSUE THREAD

**Issue by ShFil119** [rwengine/openrw#417]
There's only two things which require variables type of uint8_t. Loading assets and handling savegames. 
And bit_cast should be able to deal with them.

**Comment by dracc** [comment]
Why would this switch be a good thing? Readability?
I'm not saying that it's bad, just curious.

**Comment by ShFil119** [comment]
Char variables forbid padding, which can cause better "packaging" and higher memory IO.

**Comment by CookiePLMonster** [comment]
Do you have any specific examples in mind? Mindlessly replacing it globally sounds like a bad approach.

Not sure why you bring up padding too - it's fine if char itself is not aligned to 4 byte boundary, and it doesn't affect padding of nearby wider variables... So unless you can point out at specific code snippets which are negatively affected by use of uint8_t, this sounds useless.

**Comment by ShFil119** [comment]
I actually can think about example when uintX_t is so small (in comparison to structure) so there's padding added, int could fill it.

|uint32_t|32 bits of padding|uint64_t| all 128 bits
|int||uint64_t| also 128bits

About performance, yeah, I messed.
