### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by darkf** [rwengine/openrw#429]
(For reference I'm on Windows, have not tested on other platforms.)

When exiting the game (even before starting a new game, just via the menu) with either the menu or the titlebar close button, the game segfaults with a dereferenced null pointer.

**Comment by Lihis** [comment]
Could not reproduce in Arch Linux, tested against master (464a1e3).

**Comment by dracc** [comment]
Neither I can reproduce on Debian.

**Comment by ShFil119** [comment]
Neither I can reproduce on Arch. 

But using Appveyor's build with wine yes.

**Comment by madebr** [comment]
Cannot reproduce on Windows 10 x64 (neither using appveyor artifact or self-built one).
I can reproduce the crash on wine.

**Comment by Robo-17** [comment]
I can reproduce on Win7 x64.

**Comment by Matriks404** [comment]
I can reproduce it on Windows 10 x64 with self-built build, but not with AppVeyor ones.

**Comment by ShFil119** [comment]
```
>	rwgame.exe!GameRenderer::~GameRenderer() 169	
 	rwgame.exe!RWGame::~RWGame() 133
 	rwgame.exe!main(int argc, const char * * argv) 33	
```
And there's:
```
glDeleteFramebuffers(1, &framebufferName);
```
