### ISSUE TITLE
Game crash on start - Shader Compilation Failed

### ISSUE THREAD

**Issue by dracc** [rwengine/openrw#444]
Running `rwgame` from console, I'm getting an exception immediately.
`openrw/rwengine/src/render/OpenGLRenderer.cpp:26: [OGL] Shader Compilation Failed`

This is on b7fb22f95c4584435924f219c70781079924671f, freshly compiled.

System specs:
AMD R9 290X
Mesa 18.0.3
Debian testing
Linux 4.16.5
cmake 3.11.1

**Comment by dracc** [comment]
Okay, so, commenting out `set(OpenGL_GL_PREFERENCE GLVND)` in `CMakeLists.txt` fixed this for me.
FeelsBadMan.jpg

**Comment by ShFil119** [comment]
What's your version of cmake?

**Comment by dracc** [comment]
```
$ cmake --version
cmake version 3.11.1 ```

**Comment by Lihis** [comment]
Couldn't reproduce this with Debian Stretch:

```
Intel HD Graphics 3000
Mesa 13.0.6
cmake version 3.7.2
```

**Comment by NFSMONSTR** [comment]
Works fine:
```
Arch Linux
Kernel: 4.16.7
NVIDIA GeForce GTX 660 Ti(Proprietary driver)
Mesa 18.0.3
CMake 3.11.1
```

**Comment by dracc** [comment]
I can't reproduce this anymore either. Not sure what fixed it though. Probably something wonky with my (now replaced) system disk.
I'm closing this one.
