### ISSUE TITLE
windows issue [solved]

### ISSUE THREAD

**Issue by mythrillex** [rwengine/openrw#452]
Can someone explain how to build this in the windows to only drag&drop to game folder to works ?
i already generated the rwgame.exe but the dependencies.. dont have the link in the build wiki..
and the rep in /rwengine dont work with the exe that he generate:
avcodec-57
avdevice-57
avformat-57 etc etc.
but when start the exe give an error need avcodec-58 ..
anyway, i only want know how to build this, in vs2017 or mingw64(better)

i know.. its a noob question but if u can help

srry google translate

**Comment by ShFil119** [comment]
Maybe deps should be updated.

Could you share log or printscreen of error? Thx.

**Comment by mythrillex** [comment]
https://i.imgur.com/CNyXUgM.png thanks for fast reply

**Comment by mythrillex** [comment]
ç.ç i need some help here, im a .net dev :S 
how exactly i can build this in msvc without the deps ? or how to downgrade the packages x-x
I needed a person who had already done the build for windows, so I can understand the step by step, I'm newb with this

**Comment by darkf** [comment]
@ShFil119 I use msys2 just fine, have for years, so I dunno about that.

@mythrillex Please follow the MSYS build guide located here: https://github.com/rwengine/openrw/wiki/Building#mingw--msys

If you obtain actual errors feel free to post those.

**Comment by ShFil119** [comment]
@darkf, I work only on linux recently and on IRC only heard talk only about VS.

**Comment by mythrillex** [comment]
i follow this link and have compiled my rwgame.exe the problem is the dependencies of the exe, i cant execute without the deps

**Comment by darkf** [comment]
@mythrillex Run it from an MSYS shell and you shouldn't need them. Otherwise you need to go down a semi-complicated route of finding which dependencies it uses and where to find them.

**Comment by mythrillex** [comment]
Okay, I've done all the step by step compilation again, I downloaded the dependencies of msys, and gave "make" in the files, generated the executable, now in theory was just copying the executable to the folder of the game and open, right? the problem is that when I open it says that it is missing the dependencies. can u send a pic of ur gta3 folder ? with the openrw archives ?

https://i.imgur.com/6bwVHxt.png
https://i.imgur.com/5jJspbZ.png
