### ISSUE TITLE
Arrow marker placed in every cylinder marker

### ISSUE THREAD

**Issue by NFSMONSTR** [rwengine/openrw#454]
![img](https://i.imgur.com/cLuj4FS.jpg)
If start new game and then teleport to hideout firstly appears only arrow marker and after some time cylinder marker appears too
![img](https://i.imgur.com/Soc5l1E.jpg)

**Comment by NFSMONSTR** [comment]
It seems like it caused by the [last](https://github.com/rwengine/openrw/commit/98313141629bce1a753fe185954276b037226f8f) commit

So original code of opcode_018a was setting dislpay mode as radar only:
```c++
// Coordinate blips are not visible
data.display = BlipData::RadarOnly;
```

new code of script::createBlip always use ShowBoth dislpay mode:
```c++
data.type = type;
switch (type) {
    case BlipData::Contact:
        data.colour = 2;
        break;
    case BlipData::Coord:
        data.colour = 5;
        break;
    default:
        RW_ERROR("Unhandled blip type");
        break;
}
data.target = 0;
data.display = BlipData::ShowBoth;
```

I think `Coord ` blip type is expected to be only at radar
So I think it may be fixed like [that](https://github.com/NFSMONSTR/openrw/commit/6c76a130af30bf298e0cc81d23c68f86c7d36e8b)

**Comment by husho** [comment]
Original game sets display type ShowBoth for coordinate blip, but ignores it during rendering,
see https://www.gtamodding.com/wiki/018A
