### ISSUE TITLE
No sound in Cutscenes, affected only FFmpeg 4.0?

### ISSUE THREAD

**Issue by ShFil119** [rwengine/openrw#458]
I'll check if ffmpeg changed api behavior. Please answer if you also encounter this problem. ;)

**Comment by NFSMONSTR** [comment]
No sound in cutscenes too.

ffmpeg 4.0

**Comment by ShFil119** [comment]
I will take care about it and finally finish sfx pull.
Do we wanna use resampler or the integer decoder?

![ffmpeg](https://user-images.githubusercontent.com/7227492/40418644-3853e702-5e83-11e8-8392-bf5888524b3c.png)

**Comment by dracc** [comment]
Using the integer decoder would be one step shorter, right? In that case,
unless you want to rewrite even more stuff to get rid of the need for the
resampler, i vote for using the integer decoder.
