### ISSUE TITLE
Segfault on new game

### ISSUE THREAD

**Issue by dracc** [rwengine/openrw#462]
### What happens
Game de-references ScriptObjectType with null instance, followed by Segmentation fault.
[Backtrace](https://hastebin.com/wezuqozoto)

### What was expected?
Well, not a segfault.

### Steps to reproduce
1. Start new game
2. Skip cutscenes (not mandatory)
3. Be a brotha and drive the car.
4. Get out of the car and pick up the pistol on the house ledge at the end of the bridge.
5. Get back in car.
6. ?????
7. Segfault

### Version & Hardware
OpenRW Master/HEAD (c6f5b540)
g++ 8.1.0
Mesa 18.0.3
Debian testing
Linux 4.16.8

**Comment by husho** [comment]
Probably #336

**Comment by dracc** [comment]
It looks like you're right, @husho . Let's hope #437 is merged soon. :D

**Comment by dracc** [comment]
Closed because duplicate.
