### ISSUE TITLE
New Game

### ISSUE THREAD

**Issue by mythrillex** [rwengine/openrw#468]
![image](https://user-images.githubusercontent.com/17220199/40239751-56705fb2-5a8d-11e8-977a-040e766ad060.png)
wtf '-'
![image](https://user-images.githubusercontent.com/17220199/40239785-724c2dc4-5a8d-11e8-9c2f-ddc4c350de56.png)
![image](https://user-images.githubusercontent.com/17220199/40239931-cac6e8cc-5a8d-11e8-89ed-fb0f4a9c7fe8.png)
![image](https://user-images.githubusercontent.com/17220199/40239959-d70e591c-5a8d-11e8-97fd-77b341e1ea72.png)

**Comment by husho** [comment]
Weird door physics - #70 duplicate

**Comment by husho** [comment]
Temporary fix would be to clean up all traffic, if camera is in full fade. Don't know how original game handles that.

**Comment by danhedron** [comment]
I believe this is fixed
