### ISSUE TITLE
Bottom of main bridge is black

### ISSUE THREAD

**Issue by PureTryOut** [rwengine/openrw#49]
The bottom of the main bridge (between the start island and the "main land") is black (untextured).

![bridge texture glitch](https://i.imgur.com/p2gh2VF.png)

**Comment by PureTryOut** [comment]
It happens more reliable now (basically every time), but now it shows the proper "untextured" texture.

![rwgame_001](https://cloud.githubusercontent.com/assets/1565836/16461878/01a0987a-3e2f-11e6-9618-b750743937e2.png)

**Comment by Timofffee** [comment]
@PureTryOut fixed?

**Comment by PureTryOut** [comment]
Well, I haven't ran this game in ages, but I tested it just now and yes it seems to be fixed.
