### ISSUE TITLE
Subtitles don't go away

### ISSUE THREAD

**Issue by christooss** [rwengine/openrw#50]
Subtitles are stacked on top of each other and go away only when scene changes.

**Comment by christooss** [comment]
![untitled window_020](https://cloud.githubusercontent.com/assets/19415527/15500764/c12545e0-2199-11e6-9380-6d3799d55fb8.png)

**Comment by JayFoxRox** [comment]
Heads up.. I have worked on this in the past in https://github.com/JayFoxRox/openrw/pull/10
Anyone willing to take-over the text priorities part is welcome.

**Comment by danhedron** [comment]
This was fixed with #307
