### ISSUE TITLE
Vehicle handling is very bad

### ISSUE THREAD

**Issue by danhedron** [rwengine/openrw#524]
The current vehicle handling is simply using the built-in bullet vehicle controller. It isn't close to correct.

Reverse engineering of the forces acting on vehicles in the original game will help with improving the implementation. It is likely we will have to remove the default bullet vehicle controller and roll our own.

More detailed physics information on collision response would be helpful more generally (#416).

**Comment by ShFil119** [comment]
Cars are actually flipping, because wheel can sink in bumper, bullet tries fix it by pushing objects away. 
![](https://user-images.githubusercontent.com/7227492/40268784-81889042-5b74-11e8-85fe-93d4570ea96c.png)

Been trying to tweak parameters, but after acceptably setting parameters of suspension.
Wheels sink in ground, bullet again tries fix it by pushing  objects away.

**Comment by vflyson** [comment]
I'll pretend that I know a whole bunch about physics engines and drop this: there must be a way to "blacklist" the car's parts from affecting the physics of its own wheels.

**Comment by danhedron** [comment]
> there must be a way to "blacklist" the car's parts from affecting the physics of its own wheels.

Vehicle raycasts should already be ignoring the vehicle body as ``VehicleRaycaster`` uses a ``ClosestNotBeRayResultCallback`` to filter it out. The car's additional parts (doors, etc). are separate bodies, there may be some interaction between them and the raycast. Unless there's a problem with that, the suspension just can't hold up the car.

**Comment by ShFil119** [comment]
I'm doing tests with center of mass. When moving CoM 1m lower is doing the job with flipping, there is still problem with the back of the vehicle. Even small change of direction of travel is able to put the vehicle into circulation.
@danhedron, I'm not too much into graphics (aka OpenGL), can you add code which draws points. (For marking CoM) It should make debugging much easier.
