### ISSUE TITLE
Ownership of objects's resources should be refactored?

### ISSUE THREAD

**Issue by ShFil119** [rwengine/openrw#545]
Actually there is no any clear owner of resource like animation, clump, geometry, atomic. Using shared_ptr for them solves problem when memory should be freed. 

But it has many disadvantages:
- overhead,
- code is harder to read, maintain and refactor,
- storing and managing resources in poll is harder than could be (frankly making all kind of optimizations),

What do you think?

**Comment by husho** [comment]
These things that you listed are parts of the game object model mostly and must be owned by it. Also there should be some streaming system for models, so game won't load everything at the start and load anything if needed. Models themselves should be reference counted, so when there is no objects using them, they can be unloaded.

**Comment by ShFil119** [comment]
Yeah, we need something like our own ref counting or shared_ptr. It's inevitable.

But it isn't clear where objects are grabbing ownership and number of shared_ptr usage can be greatly reduced. I'll try to link some examples.

(I guess I should edit title.)

**Comment by ShFil119** [comment]
I'll close it and open issue per specific problem/file.
