### ISSUE TITLE
Add GLES compatibility

### ISSUE THREAD

**Issue by HelloOO7** [rwengine/openrw#557]
OpenRW compiles just fine on Raspberry Pi 3, but requires libSDL2 with GL support to work, which is possible for the RPi, but the experimental GL driver is buggy and breaks several programs when used. Using gl4es translator by ptitSeb segfaults the engine. Are there any plans of implementing GLES natively, or using a translator like nanogl the same way it was done in Xash3D?

**Comment by dracc** [comment]
Duplicate of #282 and #418

**Comment by HelloOO7** [comment]
If I understand correctly, noone is currently planning support until the engine is finished in terms of gameplay? OK, thanks.

**Comment by ShFil119** [comment]
@HelloOO7, I'd say we are discussing about switching renderer.

**Comment by HelloOO7** [comment]
Not really, I suggested using nanogl, like Xash does, though as the devs said a few months ago, they will probably look into that after they finish the gameplay.
