### ISSUE TITLE
Warnings during the compilation process (Mac)

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#59]
Hi

I want to inform you that I noticed warnings during the compilation process on the Mac:

uname -a
Darwin Grzegorzs-Mac-mini.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep 1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64

https://gist.github.com/gbudny/69b41f3c70585be421d499b2a1ebb3f6

**Comment by JayFoxRox** [comment]
Can some mac dev shed some light on this / fix it?

**Comment by paulsapps** [comment]
```
 passing 'char [14]' to parameter of type 'const GLubyte *' (aka
      'const unsigned char *') converts between pointers to integer types with
      different sign [-Wpointer-sign]
```

Exactly what it says on the tin.. casting signed char* to unsigned char*.

**Comment by JayFoxRox** [comment]
Related to #195
