### ISSUE TITLE
Game is not responding most of the time on windows

### ISSUE THREAD

**Issue by husho** [rwengine/openrw#595]
I'm using 089ab587. When I start the game, it takes like 1 minute to get to the menu. After that it's impossible to click on anything. After a while it becomes a little more responsive [still it feels like 0.5fps], so I can click on "start new game".  After starting a new game, it becomes non responsive again, there is only sound, it almost does not render any frames, after alt-tabbing I can't bring game's window back. Task manager reports that the process "Not responding" and the game uses 1 core at 100%.

**Comment by Matriks404** [comment]
Yeah I've noticed this issue too, but it takes only like 20-30 seconds for game to stabilize framerate (on intel i3 and nvidia gtx 1060, I think it took even longer on my bad laptop). I think this issue is in the master branch for few months now.

**Comment by husho** [comment]
Last master build from appveyor works fine though.

**Comment by ShFil119** [comment]
I'm not using win, but IIRC you can swap MSVC with Clang/mingw. Does it the same result?

**Comment by danhedron** [comment]
Are these debug or release builds? `-DCMAKE_BUILD_TYPE=Release`. The appveyor builds use the release configuration, and visual studio debug builds are quite a bit slower than other toolchains from what I remember.

**Comment by husho** [comment]
Debug, but it is so slow up to the point that it is impossible to do anything really.

**Comment by ShFil119** [comment]
Can you try build deps as release and openrw as debug?

**Comment by madebr** [comment]
Running the performance profiler on rwtests (in RelWithDebInfo mode) shows a lot of time in the `GameData::load` function.
![rwtests](https://user-images.githubusercontent.com/4138939/44271757-450c3c00-a23b-11e8-9753-6da00755456e.png)

**Comment by ShFil119** [comment]
Can you check this:
https://stackoverflow.com/questions/16770179/what-std-lockit-does

**Comment by madebr** [comment]
@shfil Debug builds are linked to debug c/c++ libraries. We can't mix debug and release builds. Google for the difference between MD and MDd.
However ,`RelWithDebInfo` comes very close with what we are used to on Linux: we get debugging information, it is linked to the MD; but the `RW_DEBUG` macro is not defined.

Adding those preprocessor variables causes linking errors: `_HAS_ITERATOR_DEBUGGING=0` causes `error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2'`. An error which also appears when a Release build wants to link to debug libraries.

**Comment by ShFil119** [comment]
Does it still happen on master?
