### ISSUE TITLE
Add HUD scaling for high resolutions

### ISSUE THREAD

**Issue by Robo-17** [rwengine/openrw#609]
In the example screenshots HUD scaled x2 for 1920x1080 (made in paint.net)

![rwgame 2018-08-28 03-36-28-35](https://user-images.githubusercontent.com/38327679/44684912-71faf300-aa74-11e8-8bb2-3eb9768189ba.png)

![x2](https://user-images.githubusercontent.com/38327679/44685023-a79fdc00-aa74-11e8-83af-ae24e33e9014.png)

**Comment by Matriks404** [comment]
I think we should have a gui scale configuration option in ini file, and later make it able to change by in-game option.

Alternatively we could make it a 3-option toggle:
   * small being like the one in the top screenshot
   * medium being something in between
   * large being like the one in the bottom screenshot
