### ISSUE TITLE
Mission icon on map is white square

### ISSUE THREAD

**Issue by christooss** [rwengine/openrw#61]
In original it's purple dot or small square. At least for the first mission. 

http://i.imgur.com/PaGXcEw.png

**Comment by tsjost** [comment]
![screenshot from 2016-05-24 01-10-53](https://cloud.githubusercontent.com/assets/1737876/15487623/4b2a393a-214f-11e6-9279-37801c227345.jpg)

**Comment by JayFoxRox** [comment]
I'll add this to the priority list. It makes us look like idiots and it's really simple to fix too.
It also makes it hard to play some missions as it tells you to the "green" marker even if there is none.

**Comment by JayFoxRox** [comment]
Consider this fixed (https://github.com/JayFoxRox/openrw/pull/23)

I accidently went a little overboard (thought GTA3 already had a feature only introduced in Vice City..) and also some of the code involved is more than ugly.
I'll clean it up as soon as the new script engine by danhedron is merged.
