### ISSUE TITLE
The openrw doesn't start on Mac - libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Invalid game directory path: 

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#62]
Hi

I tried to run the Mac version of Openrw, but I have this problem:

./rwgame --newgame
I [Game] Game directory: /Users/gbudny/Library/Application\ Support/Steam/SteamApps/common/grand\ theft\ auto\ 3/Grand\ Theft\ Auto\ 3.app/Contents/Resources/transgaming/c_drive/Program\ Files/Rockstar\ Games/GTAIII
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Invalid game directory path: /Users/gbudny/Library/Application\ Support/Steam/SteamApps/common/grand\ theft\ auto\ 3/Grand\ Theft\ Auto\ 3.app/Contents/Resources/transgaming/c_drive/Program\ Files/Rockstar\ Games/GTAIII
Abort trap: 6

[game]
path=/Users/gbudny/Library/Application\ Support/Steam/SteamApps/common/grand\ theft\ auto\ 3/Grand\ Theft\ Auto\ 3.app/Contents/Resources/transgaming/c_drive/Program\ Files/Rockstar\ Games/GTAIII         ; Game data path

[input]
invert_y=0                                 ; Invert camera Y

**Comment by christoph-heiss** [comment]
You need to remove the backslashes in the path.
So, just do:

[game]
path=/Users/gbudny/Library/Application Support/Steam/SteamApps/common/grand theft auto 3/Grand Theft Auto 3.app/Contents/Resources/transgaming/c_drive/Program Files/Rockstar Games/GTAIII

**Comment by gbudny** [comment]
Thanks.
