### ISSUE TITLE
Bullet takes ~60% of cpu time

### ISSUE THREAD

**Issue by ShFil119** [rwengine/openrw#622]
To do:
- determine who is the culprit (collision?, objects callbacks?)
- find an approach to fix it.

;)

**Comment by vflyson** [comment]
I'm unable to properly run the game due to this issue on the machine which I successfully used to run openrw less than 6 months ago.

**Comment by madebr** [comment]
@vflyson Apple, Linux or Windows?
@ShFil119 Would a bisect be useful? (I think we need a benchmark test for that that returns metrics)

**Comment by dracc** [comment]
On debug or release build? (Would that matter btw? :thinking_face:

**Comment by madebr** [comment]
@dracc It does on Windows.

**Comment by ShFil119** [comment]
On linux also.

**Comment by Lihis** [comment]
On my machine, on linux, even the debug build is still playable tho.

**Comment by ShFil119** [comment]
Playable in debug mode - yes. But if you want to develop, aka use asan, it becomes unusable.

**Comment by vflyson** [comment]
@madebr `Linux hostname 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux`

**Comment by ShFil119** [comment]
@vflyson what hardware?

**Comment by madebr** [comment]
I think I can reproduce a similar slowdown on my system.
When I start a new game, the fps floats around 20 to 30.
If I jump in the water, respawn on the other side of the river and run around a little, a lot of vehicles are created (looking at the console).
At the same time, the fps drops to 10 and lower and does not recover.

**Comment by FP4** [comment]
there doesnt seem to be setForceUpdateAllAabbs set to false on the btDiscreteDynamicsWorld which causes aabb and also motionStates to be calulated for all static objects, every simulation cycle, which is just ridiculous

**Comment by dracc** [comment]
Post-#660, I am back at a stable 75fps in debug-mode. :+1:

**Comment by danhedron** [comment]
Closing for now.
