### ISSUE TITLE
Protagonist can walk under water and under map

### ISSUE THREAD

**Issue by madebr** [rwengine/openrw#624]
![screenshot from 2018-09-01 03-07-44](https://user-images.githubusercontent.com/4138939/44940839-3756ca80-ad94-11e8-87b9-c0b0cc8c9ecf.png)

The protagonist is able to jump on the metro tunnels under water and not die.

**Comment by Lihis** [comment]
Yes, walking on top of the metro tunnel is possible in the original, here two different ways to get in:

https://www.youtube.com/watch?v=LD6n2tl4s64
https://www.youtube.com/watch?v=ECti703XCVw

I tested both methods on original game; former took many tries to get ambulance to correct spot but managed to get on top of the tunnel, latter I surprisingly pulled off on the first try.

**Comment by madebr** [comment]
Thanks for the research! :smile:
