### ISSUE TITLE
The openrw doesn't run on Mac - [OGL] Shader Compilation Failed

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#63]
Hi

I tried to run the Mac version of Openrw, but I have this problem:

uname -a
Darwin Grzegorzs-Mac-mini.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64

 ./rwgame --newgame
I [Game] Game directory: /Users/gbudny/Library/Application Support/Steam/SteamApps/common/grand theft auto 3/Grand Theft Auto 3.app/Contents/Resources/transgaming/c_drive/Program Files/Rockstar Games/GTAIII
Max UBO Size: 32767
UBO Alignment: 1465517600
Max batch size: 255
[OGL] Shader Compilation Failed
[OGL] Shader InfoLog(1):
ERROR: 0:2: '' :  version '130' is not supported
WARNING: 0:3: extension 'GL_ARB_explicit_attrib_location' is not supported
WARNING: 0:4: extension 'GL_ARB_uniform_buffer_object' is not supported
ERROR: 0:6: 'layout' : syntax error: syntax error

Source:

#version 130
#extension GL_ARB_explicit_attrib_location : enable
#extension GL_ARB_uniform_buffer_object : enable

layout(location = 0) in vec2 position;
out vec2 TexCoord;

uniform mat4 proj;
uniform mat4 view;
uniform mat4 model;

void main()
{
	gl_Position = proj * view * model * vec4(position, 0.0, 1.0);
	// UI space is top to bottom, so flip Y.
	TexCoord = position + vec2( 0.5 );
}

**Comment by tsjost** [comment]
A fix for this is blocked until we have replaced some parts of SFML with SDL, which should happen soon.

**Comment by tsjost** [comment]
As we've switched to OpenGL 3.3 it's now possible to run this on Mac. The extension warnings are just warnings and it runs fine anyway (see #171).

If there are no other issues preventing openrw to run properly then we can close this.

**Comment by JayFoxRox** [comment]
@gbudny .. we miss you buddy.. You did great testing in the past.

I'll close this issue due to inactivity, the issue should be fixed already.
Please open an updated issue if the problem persists.

**Comment by ikroni** [comment]
May be it will help, seems like WOTC added new visual effects thats not support in OpenGL...
`004d:fixme:d3d11:d3d11_immediate_context_Flush iface 0x3584e14 stub!
004c:fixme:d3d:create_texture_view OpenGL implementation does not support texture views.
004d:fixme:d3d11:d3d11_immediate_context_Flush iface 0x3584e14 stub!`
