### ISSUE TITLE
Vehicles start moving on their own when the player enters them

### ISSUE THREAD

**Issue by PureTryOut** [rwengine/openrw#64]
Every vehicle I enter starts moving on it's own when I enter them. Strangely enough, this issue stops happening when I try to record it (I use the application "simplescreencrecorder" to record the game window, not using the OpenGL injection method).

**Comment by PureTryOut** [comment]
It seems to have to do with me pressing the enter vehicle button quickly after releasing the shift button. It probably thinks W is still being pressed, thus moving the car forwards.

**Comment by christooss** [comment]
I got this bug to today. Car moving even without pressing any keys. 

Wierd thing is that when I alt tabed to take some random screenshot a my guy starting forward too without my input.

**Comment by TacoDeBoss** [comment]
Happens to me quite often as well.

**Comment by danhedron** [comment]
Is anyone still seeing this? The input code has changed quite a bit and I don't see this issue under #248

**Comment by PureTryOut** [comment]
I have not seen it for quite a while no, so I guess it's fixed.
