### ISSUE TITLE
Opcode 0042 should be RE

### ISSUE THREAD

**Issue by ShFil119** [rwengine/openrw#645]
"It's just float comparison. where is the problem????????"
As others opcodes `0043`, `0044`, `0045` and `0046` aren't used in script, we cannot realize this problem.

But `0042` is used for gates: 
https://github.com/Lighnat0r/GTA-III-SCM-Converted/search?q=0042&unscoped_q=0042

Problem is - how big should epsilon be?

**Comment by husho** [comment]
There is no epsilon in game's interpreter for that opcode. Just raw "=="

**Comment by ShFil119** [comment]
Thanks @husho. ^^
