### ISSUE TITLE
When taking screenshot ingame F12 minimap is missing

### ISSUE THREAD

**Issue by christooss** [rwengine/openrw#67]
Minimap is transparent. White and gray squares noting I can see background. AMD with Mesa 11.2 drivers but I think this is just screenshot function derping.

This image is screenshot of a screenshot cause imgur shows minimap (transparent/background stuff) as black I think http://imgur.com/0IqOOmC

**Comment by tsjost** [comment]
Some parts of the yellow bits in the pause menu map are also slightly transparent:

![screen02](https://cloud.githubusercontent.com/assets/1737876/15487591/fc7f0914-214e-11e6-8f54-67478cbeee27.png)

**Comment by JayFoxRox** [comment]
Screenshot functionality has been removed. Not an issue anymore.
