### ISSUE TITLE
Map is full/semi transparent when screenshotting

### ISSUE THREAD

**Issue by tsjost** [rwengine/openrw#68]
When using the built-in screenshotting tool (F12), but not with any external tools.

Transparent square:
![screen01](https://cloud.githubusercontent.com/assets/1737876/15487410/6f5cec3c-214d-11e6-8827-b4f30bbf0f7f.png)

Some parts of the yellow bits of the map are slightly transparent:
![screen02](https://cloud.githubusercontent.com/assets/1737876/15487409/6f305bfe-214d-11e6-8866-26fd87a3685e.png)

**Comment by christooss** [comment]
Duplicate of [#67](https://github.com/rwengine/openrw/issues/67) :)

**Comment by tsjost** [comment]
@christooss nice ninjaing!
