### ISSUE TITLE
A wierd circle at the end of the starting bridge

### ISSUE THREAD

**Issue by christooss** [rwengine/openrw#69]
![screenshot2](https://cloud.githubusercontent.com/assets/19415527/15487617/7e93c978-213e-11e6-8081-2b938df5a69a.png)

**Comment by TacoDeBoss** [comment]
It's also there for me after starting the first mission.

**Comment by tsjost** [comment]
Isn't that supposed to be a Rampage thing? Regardless those shouldn't appear on missions.

**Comment by PerikiyoXD** [comment]
That is an info pickup, that states the bridge will be repaired soon.

**Comment by PerikiyoXD** [comment]
![captura de pantalla 52](https://cloud.githubusercontent.com/assets/3116368/18396284/24db829c-76c3-11e6-8c15-ae24f4793bb7.png)
![Uploading Captura de pantalla (51).png…]()

**Comment by SonofUgly** [comment]
As this is working as intended, and the icon renders (almost*) correctly, this can be closed.

*The transparent effect around it is still [slightly off](https://u.nya.is/xfybrv.png).

**Comment by JayFoxRox** [comment]
Agreed. I've embedded the screenshot so it's easier to see that it looks acceptable now.
