### ISSUE TITLE
Water cannot be seen through car windows

### ISSUE THREAD

**Issue by TacoDeBoss** [rwengine/openrw#71]
When viewed through a car window, water doesn't appear.

![screenshot_2016-05-23_22-25-17](https://cloud.githubusercontent.com/assets/2870898/15491359/43fa2df6-2135-11e6-892f-a3b7c7520efa.png)

**Comment by JayFoxRox** [comment]
Can you create a better screenshot?
Press `M` while being ingame and then press `F` in that menu to get a free-flight camera (Controlled using mouse, WASD and shift)

**Comment by TacoDeBoss** [comment]
@JayFoxRox Sorry, I've been doing some things the last couple of days.
![screenshot_2016-06-08_19-10-52](https://cloud.githubusercontent.com/assets/2870898/15915188/c1dee0c6-2dac-11e6-8d99-663279d7d5b9.png)

**Comment by ShFil119** [comment]
Still happens on master. 2f8ae7fb0b5c9726c5a0a7d95c321d86ebf550a0

**Comment by vflyson** [comment]
Seems like it's been resolved by #720
