### ISSUE TITLE
Map viewer tool

### ISSUE THREAD

**Issue by swift502** [rwengine/openrw#715]
Hi,

I'm looking for a way to load the entire map of liberty city and export it in a modern 3D format (like fbx). @danhedron informed me that "OpenRW already has a map viewer tool". I built the RWViewer and expected the "World" tab to display the map, but the whole RWViewer seems somewhat incomplete / broken.

Is this what it's supposed to look like? Or did I somehow build it wrong, since I'm on a virtual machine...

[Video](https://youtu.be/rEtA5FJ3bU4)

Does OpenRW contain a map tool which reads the .ide and .ipl files and displays the entire map? 
Where do I find this map tool?
I know there's .ide and .ipl loaders? If they work I at least could write my own map tool...

Thanks.

**Comment by swift502** [comment]
Maybe it's the BUILD_TOOLS options I missed...

**Comment by swift502** [comment]
Ok not really, that only seem to be something to do with fonts..

**Comment by vflyson** [comment]
I'm also interested in being able to get the whole map as a file, e.g. to be able to 3d-print it and put on the wall.

**Comment by swift502** [comment]
@vflyson I've setup [LibertyCityConverter](https://github.com/swift502/LibertyCityConverter). I'll try simply borrowing the crucial components from OpenRW and make the simplest possible program to export the map into the simplest 3D format, with textures.

Might take months. Or forever. We'll see.

**Comment by Ryder17z** [comment]
I'd be highly interested in that file

**Comment by swift502** [comment]
@vflyson @Ryder17z I ditched OpenRW because I suck at C/C++ 😄 
I found [DragonFF](https://github.com/swift502/DragonFF), which is a Blender DFF importer, and I'm progressing quite well with that. With my extension it might be possible to import both the III and VC map.

I'll tell you guys when I have something meaningful.
