### ISSUE TITLE
Player sometimes enters wrong vehicle seat

### ISSUE THREAD

**Issue by TacoDeBoss** [rwengine/openrw#73]
Some vehicles see the player entering the back seat on the left side of the car, instead of the driver seat.
![screenshot_2016-05-23_22-38-25](https://cloud.githubusercontent.com/assets/2870898/15491546/256fef04-2137-11e6-9468-fd64c282919d.png)

**Comment by TacoDeBoss** [comment]
![screenshot_2016-05-23_22-40-34](https://cloud.githubusercontent.com/assets/2870898/15491569/619156e4-2137-11e6-981b-b936aeaf4ace.png)

**Comment by JayFoxRox** [comment]
@danhedron would we have to hardcode a list of vehicles or does the game determine the seat positions by name or is there some other black magic going on (guessing the seat position by offset from root etc?)

If so, shall we collect a list of vehicles here or look for one?
Should we document it on gtamodding instead?

**Comment by danhedron** [comment]
It'd be nice to document as much as possible since there's no OpenRW documentation besides the source. the `ped_backseat` in the taxi comes before the `ped_frontseat`, same for the barracks. Fixing the seat lookup behaviour to take the name into account should resolve this.
