### ISSUE TITLE
How compile under Slackware(64) 14.2

### ISSUE THREAD

**Issue by inukaze** [rwengine/openrw#739]
OpenRW
==============================================================

`su`
> Contraseña :

```
cd /tmp
rm -rf *
git clone https://github.com/rwengine/openrw
cd openrw
mkdir build ; cd build
cmake ..
```

> -- The C compiler identification is GNU 5.5.0
> -- The CXX compiler identification is GNU 5.5.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Building OpenRW GIT SHA1: ece3d09e29473bb95d09c969b651d0bf46109f33
> -- Found Boost: /usr/include (found version "1.59.0")  
> -- Found Boost: /usr/include (found version "1.59.0") found components: program_options system 
> -- Found Boost: /usr/include (found version "1.59.0") found components: filesystem system 
> -- Found OpenAL: /usr/lib64/libopenal.so  
> -- Found Bullet: /usr/lib64/libBulletDynamics.so  
> -- Found GLM: /usr/include (found version "0.9.9.5") 
> -- Found FFmpeg: /usr/lib64/libavcodec.so (found version "3.4.6") 
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found SDL2: /usr/local/lib/libSDL2.so (found version "2.0.10") 
> -- Found OpenGL: /usr/lib64/libGL.so   
> -- Configuring done
> CMake Error at external/imgui/CMakeLists.txt:1 (add_library):
>   Cannot find source file:
> 
>     imgui/imgui.h
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
>   .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc
> 
> 
> CMake Error at external/imgui/CMakeLists.txt:35 (add_library):
>   Cannot find source file:
> 
>     imgui/examples/imgui_impl_opengl3.h
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
>   .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc
> 
> 
> CMake Error at external/imgui/CMakeLists.txt:1 (add_library):
>   No SOURCES given to target: imgui
> 
> 
> CMake Error at external/imgui/CMakeLists.txt:35 (add_library):
>   No SOURCES given to target: imgui_sdl_gl3
> 
> 
> CMake Generate step failed.  Build files cannot be regenerated correctly
> 

`ls ./external/imgui/`

> CMakeFiles/

Missing files. from where i can get ?

**Comment by christoph-heiss** [comment]
Either initially clone with `git clone --recursive https://github.com/rwengine/openrw` or run 
```
git submodule init
git submodule update
```
in the `openrw` directory after checkout.

**Comment by inukaze** [comment]
OpenRW : 

`su`
> Contraseña :

```
cd /tmp
rm -rf *
git clone --recursive https://github.com/rwengine/openrw
cd openrw
git submodule init
git submodule update
mkdir build ; cd build

export {C,CXX}FLAGS='-O2 -fPIC -march=native -mtune=native -pipe' ; export OPTFLAGS='-O2 -fPIC -march=native -mtune=native -pipe'

cmake DCMAKE_INSTALL_PREFIX=/media/Compartido/Videojuegos/Linux/Basura/OpenRW ..
```

> -- The C compiler identification is GNU 5.5.0
> -- The CXX compiler identification is GNU 5.5.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Building OpenRW GIT SHA1: ece3d09e29473bb95d09c969b651d0bf46109f33
> -- Found Boost: /usr/include (found version "1.59.0")  
> -- Found Boost: /usr/include (found version "1.59.0") found components: program_options system 
> -- Found Boost: /usr/include (found version "1.59.0") found components: filesystem system 
> -- Found OpenAL: /usr/lib64/libopenal.so  
> -- Found Bullet: /usr/lib64/libBulletDynamics.so  
> -- Found GLM: /usr/include (found version "0.9.9.5") 
> -- Found FFmpeg: /usr/lib64/libavcodec.so (found version "3.4.6") 
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found SDL2: /usr/local/lib/libSDL2.so (found version "2.0.10") 
> -- Found OpenGL: /usr/lib64/libGL.so   
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /tmp/openrw/build

`make`

> Scanning dependencies of target rwcore
> [  1%] Building C object rwcore/CMakeFiles/rwcore.dir/gl/gl_core_3_3.c.o
> [  1%] Building CXX object rwcore/CMakeFiles/rwcore.dir/gl/DrawBuffer.cpp.o
> [  2%] Building CXX object rwcore/CMakeFiles/rwcore.dir/gl/GeometryBuffer.cpp.o
> [  3%] Building CXX object rwcore/CMakeFiles/rwcore.dir/gl/TextureData.cpp.o
> [  4%] Building CXX object rwcore/CMakeFiles/rwcore.dir/rw/abort.cpp.o
> [  5%] Building CXX object rwcore/CMakeFiles/rwcore.dir/platform/FileIndex.cpp.o
> /tmp/openrw/rwcore/platform/FileIndex.cpp: En la función miembro ‘void FileIndex::indexTree(const boost::filesystem::path&)’:
> /tmp/openrw/rwcore/platform/FileIndex.cpp:24:40: error: ‘class boost::filesystem::path’ has no member named ‘lexically_normal’
>      rwfs::path basePath = (path / ".").lexically_normal();
>                                         ^
> /tmp/openrw/rwcore/platform/FileIndex.cpp:32:29: error: ‘const class boost::filesystem::path’ has no member named ‘lexically_relative’
>          auto relPath = path.lexically_relative(basePath);
>                              ^
> rwcore/CMakeFiles/rwcore.dir/build.make:146: fallo en las instrucciones para el objetivo 'rwcore/CMakeFiles/rwcore.dir/platform/FileIndex.cpp.o'
> make[2]: *** [rwcore/CMakeFiles/rwcore.dir/platform/FileIndex.cpp.o] Error 1
> CMakeFiles/Makefile2:250: fallo en las instrucciones para el objetivo 'rwcore/CMakeFiles/rwcore.dir/all'
> make[1]: *** [rwcore/CMakeFiles/rwcore.dir/all] Error 2
> Makefile:170: fallo en las instrucciones para el objetivo 'all'
> make: *** [all] Error 2

Which i need to do, for generate the binary executable file ?

**Comment by christoph-heiss** [comment]
> -- The C compiler identification is GNU 5.5.0
> -- The CXX compiler identification is GNU 5.5.0
> [..]
> -- Found Boost: /usr/include (found version "1.59.0")
> -- Found Boost: /usr/include (found version "1.59.0") found components: program_options system
> -- Found Boost: /usr/include (found version "1.59.0") found components: filesystem system

You are running a **really** old system. GCC 5.5 is about 3.5 years old, Boost 1.59.0 about 6 years.

OpenRW needs a recent toolchain (GCC 8.3+ _maybe could_ work if configuring with `-DFILESYSTEM_LIBRARY=CXX17` or `-DFILESYSTEM_LIBRARY=CXXTS`, but chances are better with GCC 10.x.y+).

Cannot really help you further than that, other than suggesting upgrading your system.

**Comment by tsjost** [comment]
I checked out slackware64-current and it's still way too old unfortunately, so not much we can do about that sadly :(
But by the time we hit 1.0, Slackware should be able to build the project! :D
