### ISSUE TITLE
About Grand Theft Auto III decompiled

### ISSUE THREAD

**Issue by aaferrari** [rwengine/openrw#745]
I'm not sure if anyone else asked this before, but I recently discovered that GTA III was decompiled last year. The code is still available at https://github.com/td512/re3 and I had the following question: Would it be possible to use it for this project (at least as a reference when implementing certain features)?

**Comment by dracc** [comment]
"no longer needed" is a very thin stretch, seeing as re3 was struck by DMCA claims and taken down in the past.
Main repository is managed by the user/group/? @gtamodding, what you've shared is merely a (gray area if not downright illegal) re-up.

Closer to the truth would be that re3 is the reason most people _lost interest_ in openrw.

**Comment by X-Seti** [comment]
How fair is the Vice City or SA from being open? Like openrw for gta3?


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GrimPixel** [comment]
People can consider establishing something new instead of sticking to proprietary contents. We need a framework to build virtual worlds with non-proprietary contents. The modding community is so powerful. I guess there could be little to no technical problems.

**Comment by Dygear** [comment]
This should be closed as not-an-issue.
