### ISSUE TITLE
The installation process of Openrw on Linux and Mac

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#78]
Hi

I know that you did not publish any official alpha or beta version of this game.

Do you plan to simplify the installation process of Openrw on Linux nad Mac?

For example, smplayer has a script that could create a deb packages. I personally use a very primitive script to compile new versions of Freeablo on Mac. 

```
#!/bin/bash
cd Desktop/
mkdir Diablo1
cd Diablo1
git clone https://github.com/wheybags/freeablo.git
cd freeablo 
git submodule update --init
cd ..
mkdir build
cd build
ln -s ../freeablo/resources
export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.6.0/
cmake ../freeablo
make
./launcher
```

I think it will be nice to have this one script that will do things like: check installed packages, compile the game, create a deb, snappy package or dmg image, install and creates shortcuts on the Desktop.

(Markup fixed by JayFoxRox)

**Comment by tjbp** [comment]
Don't know anything about Macs, but Linux distro communities take care of software packaging downstream - a Debian packaging script should be contributed directly to the Debian project.

**Comment by parkerlreed** [comment]
The install for Linux isn't that complicated https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openrw-git

As mentioned install scripts/packages can easily be created for various distros.

**Comment by gbudny** [comment]
I am thinking about the script inside of the directory with the source code of the game like in this example:

https://www.assembla.com/spaces/smplayer/subversion/source/HEAD/smplayer/trunk

In this case, users can compile Openrw with all of the changes that were made eg. an hour or two days ago. Linux distro communities sometimes need many months to prepare a package for specific distributions.

**Comment by tjbp** [comment]
Preparing a package doesn't take much time, but certain distros require a degree of package maturity for reasons of stability - eg. Debian and its derivatives. If you're after bleeding-edge versions of software, you're better off with a distro like Arch - the package @parkerlreed mentioned above will clone the various latest version as part of the build & installation process. A script for people using the wrong kind of distro would be a pain for devs to maintain, or a pain for users once it goes out of date - package manager ecosystems are designed as a solution to this.

**Comment by gbudny** [comment]
Luckily, this issue doesn't exist in the case of Mac OS X because Mac users usually use one of the two latest versions. However, this script could be done only for two popular Linux distributions e.g. Ubuntu (deb or snappy) and Fedora (rpm) which will be easier for devs to maintain it .

**Comment by PureTryOut** [comment]
Packaging should be done by seperately from development. If you want easy install, make the repositories yourself, or get someone else to do it, but do not expect the devs to do it in the repo itself.

Once a first stable version is hit, distro's will probably take it upon theirselves to package it and distribute it under their users.

**Comment by JayFoxRox** [comment]
Yes, packaging should be done by each distro on Linux.
You can still add a script like this for OpenRW to a wiki page about packaging.

However I'll close this because it's not an actual issue.
