### ISSUE TITLE
Deferred renderering

### ISSUE THREAD

**Issue by danhedron** [rwengine/openrw#8]
The deferred rendering pipeline isn't merged with the main development branch yet

**Comment by JayFoxRox** [comment]
I think we can ditch this?

It's not an integral part to the recreation of the game and it's easier to recreate the original look and feel with a traditional renderer. Lately we've even been discussing replacing the renderer with librw by @aap, so chances are this wouldn't see much use.

(If anybody really wants to work on a deferred renderer, they can probably do so in librw?)

**Comment by JayFoxRox** [comment]
I'll close this for reasons stated above.
