### ISSUE TITLE
Compile fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by gnarlin** [rwengine/openrw#82]
CMake Error at CMakeLists.txt:69 (find_package):
  Could not find a package configuration file provided by "glm" with any of
  the following names:

    glmConfig.cmake
    glm-config.cmake

  Add the installation prefix of "glm" to CMAKE_PREFIX_PATH or set "glm_DIR"
  to a directory containing one of the above files.  If "glm" provides a
  separate development package or SDK, be sure it has been installed.

**Comment by danhedron** [comment]
The ubuntu package libglm-dev seems to be missing the cmake configuration file, building GLM from source will provide that for you.

**Comment by gbudny** [comment]
You can use cmake-gui to compile glm:

sudo apt-get install cmake-qt-gui

**Comment by danhedron** [comment]
FindGLM.cmake has been included, it should now be possible to build with the libglm-dev package.

**Comment by JayFoxRox** [comment]
Does it work now @gnarlin ?
I'll close this if there is no response soon.

**Comment by gnarlin** [comment]
On fös 10.jún 2016 13:00, Jannik Vogel wrote:
> Does it work now @gnarlin <https://github.com/gnarlin> ?
> I'll close this if there is no response soon.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rwengine/openrw/issues/82#issuecomment-225175545>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AId9RZEENAUd0yUss6hCw5u_4_n8QTOfks5qKV_tgaJpZM4Il-j8>.
>
I'm at work. I'll try as soon as I get back home. Thank you very much!

**Comment by gnarlin** [comment]
It compiles now, but with lots of warnings.
http://pastebin.com/nTzj3Afs
This issue at least can be closed.

**Comment by zdgithub** [comment]
> You can use cmake-gui to compile glm:
> 
> sudo apt-get install cmake-qt-gui
I faced the same problem. After installing the cmake-qt-gui, how to compile glm? What's the commands?

**Comment by zdgithub** [comment]
> Are you sure that you have installed `libglm-dev`?

Yes
![image](https://user-images.githubusercontent.com/24309565/50553346-ffc74300-0cdf-11e9-9dda-37494a77d698.png)

**Comment by ShFil119** [comment]
It looks like super old glm. Can you try to get dependency via conan? 
https://github.com/rwengine/openrw/wiki/Building#using-conan

**Comment by zdgithub** [comment]
> It looks like super old glm. Can you try to get dependency via conan?
> https://github.com/rwengine/openrw/wiki/Building#using-conan

I installed the conan, but when executing `conan install .. -a x86_64 -s build_type=Release`, I got the error:
```
usage: conan install [-h] [-g GENERATOR] [-if INSTALL_FOLDER] [-m [MANIFESTS]]
                     [-mi [MANIFESTS_INTERACTIVE]] [-v [VERIFY]]
                     [--no-imports] [-j JSON] [-b [BUILD]] [-e ENV]
                     [-o OPTIONS] [-pr PROFILE] [-r REMOTE] [-s SETTINGS] [-u]
                     path_or_reference
conan install: error: unrecognized arguments: -a x86_64
ERROR: Exiting with code: 2
```

**Comment by madebr** [comment]
Oops, I've added these instructions recently and I introduced a little bug apparently.
The instructions should be:
```
conan install -s arch=x86_64 -s build_type=Release
cmake .. -DUSE_CONAN=ON -L
```
