### ISSUE TITLE
Add ability to flip/reset car in test mode

### ISSUE THREAD

**Issue by parkerlreed** [rwengine/openrw#83]
I get in the sports car to go testing in places and half of the time end up flipping it over. With no respawn/reset, the game has to be closed fully just to start over.

**Comment by PureTryOut** [comment]
I think eventually a method should be implemented to flip the cars like current GTA games do it: steer either left or right to slowly flip over the car that way.

**Comment by JayFoxRox** [comment]
This was done by #106
