### ISSUE TITLE
Openrw crash - Illegal Instruction 01b2 encountered at offset 1422a on thread FISHGEN

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#84]
Hi

I was driving the car in the first mission of the game, and the Openrw crashed in the same place twice:

./rwgame 
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 32 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false
Created: version = 3.3 ; depth bits = 24 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false
I [Game] Game directory: /home/gbudny/GTAIII
Max UBO Size: 65536
UBO Alignment: 256
Max batch size: 512
I [Renderer] OpenGL Renderer Version: 3.3.0 NVIDIA 340.96 (GLSL 3.30 NVIDIA via Cg compiler) Vendor: NVIDIA Corporation
I [Data] Loaded 42 zones from /home/gbudny/GTAIII/data/gta3.zon
I [Game] Started
Fstat failed ()
I [World] Loaded cutscene: BET
Fstat failed ()
I [World] Loaded cutscene: JB
I [World] Creating Vehicle ID 116 (POLICAR)
I [World] Creating Vehicle ID 117 (ENFORCR)
I [World] Creating Vehicle ID 130 (RUMPO)
I [World] Creating Vehicle ID 96 (PATRIOT)
I [World] Creating Vehicle ID 110 (TAXI)
I [World] Creating Vehicle ID 105 (CHEETAH)
I [World] Creating Vehicle ID 92 (STINGER)
I [World] Creating Vehicle ID 105 (CHEETAH)
I [World] Creating Vehicle ID 92 (STINGER)
I [World] Creating Vehicle ID 111 (KURUMA)
I [World] Creating Vehicle ID 110 (TAXI)
I [World] Creating Vehicle ID 111 (KURUMA)
I [World] Creating Vehicle ID 110 (TAXI)
I [World] Creating Vehicle ID 111 (KURUMA)
I [World] Creating Vehicle ID 111 (KURUMA)
I [World] Creating Vehicle ID 116 (POLICAR)
I [World] Creating Vehicle ID 116 (POLICAR)
Fstat failed ()
I [World] Loaded cutscene: L1_LG
Illegal Instruction 01b2 encountered at offset 1422a on thread FISHGEN
E [Script] Illegal Instruction 01b2 encountered at offset 1422a on thread FISHGEN
terminate called after throwing an instance of 'IllegalInstruction'
Aborted (core dumped)

Do you need a screenshot of this place in the game?

**Comment by danhedron** [comment]
The location and any other steps needed to cause the crash.

**Comment by PureTryOut** [comment]
Reproduced here as well. Was driving in my car on the way to pick up Luigi's Girls. I went on a road under the bridge and just passed the bridge.

**Comment by gbudny** [comment]
Here is a screenshoot;

http://picpaste.com/Untitled-KoGd6FAa.png

uname -a
Linux gbudny-Macmini 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by JayFoxRox** [comment]
This should happen when the player is close to the Fish Factory.
The thread FISHGEN will wait until the player is in the zone PORT_W and create triads with guns in their hands (which is not supported yet).
There should also be bugs when trying to drive through the tramp tunnel etc.

[The code can be found here](http://gtamodding.ru/wiki/Genstuf)

This is closely related to #90 where the same happens with the import / export garage in the zone of the docks.
