### ISSUE TITLE
Error at cmake/external/inih.cmake:8 (add_library):   Cannot find source file:

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#88]
Hi

I noticed this issue when I tried to compile the new version of openrw:

cmake ../ -DCMAKE_BUILD_TYPE=Release
-- Found SFML 2.3.2 in /usr/include
-- Found MAD in /usr/include
-- Configuring done
CMake Error at cmake/external/inih.cmake:8 (add_library):
  Cannot find source file:

    /home/gbudny/Downloads/openrw-master/external/inih/ini.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/external/CMakeLists.txt:5 (include)

CMake Error: Cannot determine link language for target "inih".
CMake Error: CMake can not determine linker language for target: inih
-- Generating done
-- Build files have been written to: /home/gbudny/Downloads/openrw-master/build

**Comment by TacoDeBoss** [comment]
Also happening to me. Running Debian Sid/Kernel 4.6.0

**Comment by tsjost** [comment]
As of #87 inih is now a submodule instead of being pulled automagically by cmake. You'll have to run `git submodule init && git submodule update` to pull down inih. You'll also probably have to clean your build directory, rerun cmake and do a clean build.

**Comment by TacoDeBoss** [comment]
@tsjost Build compiles fine now. Many thanks.

**Comment by gbudny** [comment]
Can you tell me in which directory should should I type this command?

git submodule init && git submodule update
fatal: Not a git repository (or any of the parent directories): .git

**Comment by gbudny** [comment]
Thanks

**Comment by gbudny** [comment]
I think that there should be the information about this command in this file:

https://github.com/rwengine/openrw/wiki/Getting-Started

**Comment by parkerlreed** [comment]
@gbudny There already is https://github.com/rwengine/openrw/wiki/Building#build which is the top link on the page you linked.
