### ISSUE TITLE
The radar doesn't blink in the first mission

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#97]
Hi

I noticed that in this moment the radar should blink for a couple of seconds:

5:00 - 5:05 

https://www.youtube.com/watch?v=RoQStKto_n4

**Comment by JayFoxRox** [comment]
This happens due to [opcode 03E7](http://www.gtamodding.com/wiki/03E7) only being stubbed

**Comment by dracc** [comment]
The Radar blinks now. [Video](https://youtu.be/xCPa9SdRtGk) (3:07-3:12)
Not sure how long this has been working though. Mark as fixed?
